/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
!!GlobalInfo
product: Pins v13.1
processor: MIMXRT1176xxxxx
package_id: MIMXRT1176DVMAA
mcu_data: ksdk2_0
processor_version: 13.0.2
board: MIMXRT1170-EVK
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */

#include "fsl_common.h"
#include "fsl_iomuxc.h"
#include "fsl_gpio.h"
#include "board.h"
#include "pin_mux.h"
#include <FreeRTOS.h>

#define  CONFIGURE_ANALOG_INPUTS  0
/* FUNCTION ************************************************************************************************************
 * 
 * Function Name : BOARD_InitBootPins
 * Description   : Calls initialization functions.
 * 
 * END ****************************************************************************************************************/
 
void BOARD_InitBootPins(void) {

    BOARD_InitLpuartPins();       /* Debug console*/
    BOARD_InitMipiPanelPins();
    BOARD_InitFlashPins();
    BOARD_InitFlexCANPins();
    BOARD_InitRtcI2cPins();
    BOARD_InitGpioPins();
    BOARD_InitAnalogPin();


}

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitLpuartPins, assigned for the Cortex-M7F core.
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void BOARD_InitLpuartPins(void) {

	CLOCK_EnableClock(kCLOCK_Iomuxc);
	CLOCK_EnableClock(kCLOCK_Iomuxc_Lpsr);

	IOMUXC_SetPinMux( IOMUXC_GPIO_AD_24_LPUART1_TXD, 0U);

	IOMUXC_SetPinMux(IOMUXC_GPIO_AD_25_LPUART1_RXD, 0U);
}



/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitMipiPanelPins, assigned for the Cortex-M7F core.
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void BOARD_InitMipiPanelPins(void) {

	CLOCK_EnableClock(kCLOCK_Iomuxc);
	CLOCK_EnableClock(kCLOCK_Iomuxc_Lpsr);


	IOMUXC_SetPinMux(CLUSTER_DISPLAY_BL_BANK,0U);  //backlight

	IOMUXC_SetPinMux(CLUSTER_DISPLAY_DRIVER_BANK,0U);  //display driver

	IOMUXC_SetPinMux(CLUSTER_DISPLAY_RST_BANK,0U);  //Reset

	IOMUXC_SetPinMux(CLUSTER_DISPLAY_STB_BANK,0U);   //standby
}

void BOARD_InitFlashPins(void)
{
	//Flash start
	IOMUXC_SetPinMux(IOMUXC_GPIO_AD_29_GPIO9_IO28,0U);

	IOMUXC_SetPinMux(IOMUXC_GPIO_AD_30_GPIO9_IO29,0U);

	IOMUXC_SetPinMux(IOMUXC_GPIO_AD_31_GPIO9_IO30,0U);

	IOMUXC_SetPinMux(IOMUXC_GPIO_AD_28_GPIO9_IO27,0U);
	//Flash End
}


void BOARD_InitFlexCANPins(void)
{
	// CAN
	IOMUXC_SetPinMux(IOMUXC_GPIO_LPSR_00_FLEXCAN3_TX,1U);
	IOMUXC_SetPinMux(IOMUXC_GPIO_LPSR_01_FLEXCAN3_RX,1U);

	IOMUXC_SetPinConfig(IOMUXC_GPIO_LPSR_00_FLEXCAN3_TX,0x02U);
	IOMUXC_SetPinConfig(IOMUXC_GPIO_LPSR_01_FLEXCAN3_RX,0x02U);
}


void BOARD_InitRtcI2cPins(void)
{
#if(HW_REV_VERSION != 1)
	/*GPIO configuration of RTC_Enable on GPIO_AD_13 (pin L12) */
	gpio_pin_config_t RTC_Enable_config = {
							  .direction = kGPIO_DigitalOutput,
							  .outputLogic = 1U,
							  .interruptMode = kGPIO_NoIntmode
						};

	IOMUXC_SetPinMux(IOMUXC_GPIO_AD_13_GPIO9_IO12,0U);
	GPIO_PinInit(GPIO9, 12U, &RTC_Enable_config);


#endif
	//I2C START
	IOMUXC_SetPinMux(IOMUXC_GPIO_AD_32_LPI2C1_SCL,1U);
	IOMUXC_SetPinMux(IOMUXC_GPIO_AD_33_LPI2C1_SDA,1U);
	IOMUXC_SetPinMux(IOMUXC_GPIO_SD_B1_05_GPIO10_IO08,1U);
	//I2C END
}

void BOARD_InitBlePins(void)
{
	//BLE
	IOMUXC_SetPinMux(IOMUXC_GPIO_AD_15_LPUART10_TXD,0U);
	IOMUXC_SetPinMux(IOMUXC_GPIO_AD_16_LPUART10_RXD,0U);
	IOMUXC_SetPinMux(IOMUXC_GPIO_AD_34_LPUART10_CTS_B,0U);
	IOMUXC_SetPinMux(IOMUXC_GPIO_AD_35_LPUART10_RTS_B,0U);

	//BLE End
}

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitGpioPins, assigned for the Cortex-M7F core.
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void BOARD_InitGpioPins(void) {
#if 0
  CLOCK_EnableClock(kCLOCK_Iomuxc);           /* LPCG on: LPCG is ON. */

  /* GPIO configuration of SIM1_PD on GPIO_AD_04 (pin M13) */
  gpio_pin_config_t SIM1_PD_config = {
      .direction = kGPIO_DigitalOutput,
      .outputLogic = 0U,
      .interruptMode = kGPIO_NoIntmode
  };
  /* Initialize GPIO functionality on GPIO_AD_04 (pin M13) */
  GPIO_PinInit(GPIO9, 3U, &SIM1_PD_config);

  /* GPIO configuration of USER_BUTTON on WAKEUP_DIG (pin T8) */
  gpio_pin_config_t USER_BUTTON_config = {
      .direction = kGPIO_DigitalInput,
      .outputLogic = 0U,
      .interruptMode = kGPIO_IntRisingEdge
  };
  /* Initialize GPIO functionality on WAKEUP_DIG (pin T8) */
  GPIO_PinInit(GPIO13, 0U, &USER_BUTTON_config);
  /* Enable GPIO pin interrupt on WAKEUP_DIG (pin T8) */
  GPIO_PortEnableInterrupts(GPIO13, 1U << 0U);

  IOMUXC_SetPinMux(IOMUXC_GPIO_AD_04_GPIO9_IO03,  0U);
  IOMUXC_SetPinMux(IOMUXC_WAKEUP_DIG_GPIO13_IO00, 0U);
#endif
}

void BOARD_InitAnalogPin(void)
{
#if CONFIGURE_ANALOG_INPUTS
	/* GPIO configuration on GPIO_AD_13 (pin L12) */
	  gpio_pin_config_t gpio9_pinL12_config = {
	      .direction = kGPIO_DigitalInput,
	      .outputLogic = 0U,
	      .interruptMode = kGPIO_NoIntmode
	  };

	  IOMUXC_SetPinMux(IOMUXC_GPIO_AD_13_GPIO9_IO12,1U);
	  IOMUXC_SetPinConfig(IOMUXC_GPIO_AD_13_GPIO9_IO12,0x0EU);
	  GPIO_PinInit(GPIO9, 12U, &gpio9_pinL12_config);
#else

	IOMUXC_SetPinConfig(IOMUXC_GPIO_AD_12_GPIO9_IO11,0x06U);
	IOMUXC_SetPinConfig(IOMUXC_GPIO_AD_13_GPIO9_IO12,0x06U);
	IOMUXC_SetPinConfig(IOMUXC_GPIO_AD_14_GPIO9_IO13,0x06U);
	IOMUXC_SetPinConfig(IOMUXC_GPIO_LPSR_06_LPI2C6_SDA, 0x02U);
	IOMUXC_SetPinConfig(IOMUXC_GPIO_LPSR_07_LPI2C6_SCL,0x02U);
	IOMUXC_SetPinConfig(IOMUXC_GPIO_AD_17_GPIO9_IO16,0x06U);
	IOMUXC_SetPinConfig(IOMUXC_WAKEUP_DIG_GPIO13_IO00,0x0EU);
#endif
}
/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
