// This code is auto-generated by Qul's qulrcc tool.
// WARNING! All changes made in this file will be lost!
#include <qul/private/graphicsdevice.h>


// file path :/assets/1024x600/icon_lowbeam.png 

static Qul::Private::RasterBuffer qul_rasterBuffer_icon_5Flowbeam_4238623879086857656 = {
    0xff00ff00,
    51,
    51,
    0,
    NULL
};
extern const Qul::Private::RasterBuffer * const qul_rasterBuffer_icon_5Flowbeam_4238623879086857656_handle;
const Qul::Private::RasterBuffer * const qul_rasterBuffer_icon_5Flowbeam_4238623879086857656_handle = &qul_rasterBuffer_icon_5Flowbeam_4238623879086857656;


