// This code is auto-generated by Qul's qulrcc tool.
// WARNING! All changes made in this file will be lost!
#include <qul/private/graphicsdevice.h>


// file path :/assets/1024x600/console_bottom.png 

static Qul::Private::RasterBuffer qul_rasterBuffer_console_5Fbottom_11656608417757482220 = {
    0xffffffff,
    480,
    20,
    0,
    NULL
};
extern const Qul::Private::RasterBuffer * const qul_rasterBuffer_console_5Fbottom_11656608417757482220_handle;
const Qul::Private::RasterBuffer * const qul_rasterBuffer_console_5Fbottom_11656608417757482220_handle = &qul_rasterBuffer_console_5Fbottom_11656608417757482220;


