// This code is auto-generated by Qul's qulrcc tool.
// WARNING! All changes made in this file will be lost!
#include <qul/private/graphicsdevice.h>


// file path :/assets/1024x600/console_top.png 

static Qul::Private::RasterBuffer qul_rasterBuffer_console_5Ftop_16956650710360509650 = {
    0xffffffff,
    480,
    60,
    0,
    NULL
};
extern const Qul::Private::RasterBuffer * const qul_rasterBuffer_console_5Ftop_16956650710360509650_handle;
const Qul::Private::RasterBuffer * const qul_rasterBuffer_console_5Ftop_16956650710360509650_handle = &qul_rasterBuffer_console_5Ftop_16956650710360509650;


