// This code is auto-generated by Qul's qulrcc tool.
// WARNING! All changes made in this file will be lost!
#include <qul/private/graphicsdevice.h>


// file path :/assets/1024x600/icon_sport.png 

static Qul::Private::RasterBuffer qul_rasterBuffer_icon_5Fsport_12188040122751549104 = {
    0xffffffff,
    44,
    45,
    0,
    NULL
};
extern const Qul::Private::RasterBuffer * const qul_rasterBuffer_icon_5Fsport_12188040122751549104_handle;
const Qul::Private::RasterBuffer * const qul_rasterBuffer_icon_5Fsport_12188040122751549104_handle = &qul_rasterBuffer_icon_5Fsport_12188040122751549104;


