// This code is auto-generated by Qul's qulrcc tool.
// WARNING! All changes made in this file will be lost!
#include <qul/private/graphicsdevice.h>


// file path :/assets/1024x600/icon_coolanttemp.png 

static Qul::Private::RasterBuffer qul_rasterBuffer_icon_5Fcoolanttemp_13764094077854101002 = {
    0xffffffff,
    56,
    60,
    0,
    NULL
};
extern const Qul::Private::RasterBuffer * const qul_rasterBuffer_icon_5Fcoolanttemp_13764094077854101002_handle;
const Qul::Private::RasterBuffer * const qul_rasterBuffer_icon_5Fcoolanttemp_13764094077854101002_handle = &qul_rasterBuffer_icon_5Fcoolanttemp_13764094077854101002;


