// This code is auto-generated by Qul's qulrcc tool.
// WARNING! All changes made in this file will be lost!
#include <qul/private/graphicsdevice.h>


// file path :/assets/1024x600/icon_airbag.png 

static Qul::Private::RasterBuffer qul_rasterBuffer_icon_5Fairbag_3645947267865513010 = {
    0xffffffff,
    50,
    48,
    0,
    NULL
};
extern const Qul::Private::RasterBuffer * const qul_rasterBuffer_icon_5Fairbag_3645947267865513010_handle;
const Qul::Private::RasterBuffer * const qul_rasterBuffer_icon_5Fairbag_3645947267865513010_handle = &qul_rasterBuffer_icon_5Fairbag_3645947267865513010;


