// This code is auto-generated by Qul's qulrcc tool.
// WARNING! All changes made in this file will be lost!
#include <qul/private/graphicsdevice.h>


// file path :/assets/1024x600/icon_servicedisconnect.png 

static Qul::Private::RasterBuffer qul_rasterBuffer_icon_5Fservicedisconnect_7092547091065046762 = {
    0xffffffff,
    60,
    43,
    0,
    NULL
};
extern const Qul::Private::RasterBuffer * const qul_rasterBuffer_icon_5Fservicedisconnect_7092547091065046762_handle;
const Qul::Private::RasterBuffer * const qul_rasterBuffer_icon_5Fservicedisconnect_7092547091065046762_handle = &qul_rasterBuffer_icon_5Fservicedisconnect_7092547091065046762;


