// This code is auto-generated by Qul's qulrcc tool.
// WARNING! All changes made in this file will be lost!
#include <qul/private/graphicsdevice.h>


// file path :/assets/1024x600/logo_qucev.png 

static Qul::Private::RasterBuffer qul_rasterBuffer_logo_5Fqucev_5875142839659060269 = {
    0xffffffff,
    175,
    61,
    0,
    NULL
};
extern const Qul::Private::RasterBuffer * const qul_rasterBuffer_logo_5Fqucev_5875142839659060269_handle;
const Qul::Private::RasterBuffer * const qul_rasterBuffer_logo_5Fqucev_5875142839659060269_handle = &qul_rasterBuffer_logo_5Fqucev_5875142839659060269;


