// This code is auto-generated by Qul's qulrcc tool.
// WARNING! All changes made in this file will be lost!
#include <qul/private/graphicsdevice.h>


// file path :/assets/1024x600/icon_steeringworking.png 

static Qul::Private::RasterBuffer qul_rasterBuffer_icon_5Fsteeringworking_9269225029557674249 = {
    0xffffffff,
    65,
    52,
    0,
    NULL
};
extern const Qul::Private::RasterBuffer * const qul_rasterBuffer_icon_5Fsteeringworking_9269225029557674249_handle;
const Qul::Private::RasterBuffer * const qul_rasterBuffer_icon_5Fsteeringworking_9269225029557674249_handle = &qul_rasterBuffer_icon_5Fsteeringworking_9269225029557674249;


