// This code is auto-generated by Qul's qulrcc tool.
// WARNING! All changes made in this file will be lost!
#include <qul/private/graphicsdevice.h>


// file path :/assets/1024x600/icon_hillhold.png 

static Qul::Private::RasterBuffer qul_rasterBuffer_icon_5Fhillhold_9436492525155914948 = {
    0xffffffff,
    80,
    61,
    0,
    NULL
};
extern const Qul::Private::RasterBuffer * const qul_rasterBuffer_icon_5Fhillhold_9436492525155914948_handle;
const Qul::Private::RasterBuffer * const qul_rasterBuffer_icon_5Fhillhold_9436492525155914948_handle = &qul_rasterBuffer_icon_5Fhillhold_9436492525155914948;


