// This code is auto-generated by Qul's qulrcc tool.
// WARNING! All changes made in this file will be lost!
#include <qul/private/graphicsdevice.h>


// file path :/assets/1024x600/bg_battery.png 

static Qul::Private::RasterBuffer qul_rasterBuffer_bg_5Fbattery_18233697090329415576 = {
    0xffffffff,
    158,
    70,
    0,
    NULL
};
extern const Qul::Private::RasterBuffer * const qul_rasterBuffer_bg_5Fbattery_18233697090329415576_handle;
const Qul::Private::RasterBuffer * const qul_rasterBuffer_bg_5Fbattery_18233697090329415576_handle = &qul_rasterBuffer_bg_5Fbattery_18233697090329415576;


