// This code is auto-generated by Qul's qulrcc tool.
// WARNING! All changes made in this file will be lost!
#include <qul/private/graphicsdevice.h>


// file path :/assets/1024x600/icon_maxspeed.png 

static Qul::Private::RasterBuffer qul_rasterBuffer_icon_5Fmaxspeed_8254468392654897759 = {
    0xffffffff,
    58,
    60,
    0,
    NULL
};
extern const Qul::Private::RasterBuffer * const qul_rasterBuffer_icon_5Fmaxspeed_8254468392654897759_handle;
const Qul::Private::RasterBuffer * const qul_rasterBuffer_icon_5Fmaxspeed_8254468392654897759_handle = &qul_rasterBuffer_icon_5Fmaxspeed_8254468392654897759;


