// This code is auto-generated by Qul's qulrcc tool.
// WARNING! All changes made in this file will be lost!
#include <qul/private/graphicsdevice.h>


// file path :/assets/1024x600/icon_tempunit.png 

static Qul::Private::RasterBuffer qul_rasterBuffer_icon_5Ftempunit_6406722246781797442 = {
    0xffffffff,
    33,
    37,
    0,
    NULL
};
extern const Qul::Private::RasterBuffer * const qul_rasterBuffer_icon_5Ftempunit_6406722246781797442_handle;
const Qul::Private::RasterBuffer * const qul_rasterBuffer_icon_5Ftempunit_6406722246781797442_handle = &qul_rasterBuffer_icon_5Ftempunit_6406722246781797442;


