// This code is auto-generated by Qul's qulrcc tool.
// WARNING! All changes made in this file will be lost!
#include <qul/private/graphicsdevice.h>


// file path :/assets/1024x600/bg_range.png 

static Qul::Private::RasterBuffer qul_rasterBuffer_bg_5Frange_5054703357876000134 = {
    0xffffffff,
    115,
    100,
    0,
    NULL
};
extern const Qul::Private::RasterBuffer * const qul_rasterBuffer_bg_5Frange_5054703357876000134_handle;
const Qul::Private::RasterBuffer * const qul_rasterBuffer_bg_5Frange_5054703357876000134_handle = &qul_rasterBuffer_bg_5Frange_5054703357876000134;


