// This code is auto-generated by Qul's qulrcc tool.
// WARNING! All changes made in this file will be lost!
#include <qul/private/graphicsdevice.h>


// file path :/assets/1024x600/icon_limphome.png 

static Qul::Private::RasterBuffer qul_rasterBuffer_icon_5Flimphome_2074430016763099219 = {
    0xffffffff,
    50,
    48,
    0,
    NULL
};
extern const Qul::Private::RasterBuffer * const qul_rasterBuffer_icon_5Flimphome_2074430016763099219_handle;
const Qul::Private::RasterBuffer * const qul_rasterBuffer_icon_5Flimphome_2074430016763099219_handle = &qul_rasterBuffer_icon_5Flimphome_2074430016763099219;


