// This code is auto-generated by Qul's qulrcc tool.
// WARNING! All changes made in this file will be lost!
#include <qul/private/graphicsdevice.h>


// file path :/assets/1024x600/icon_thernalrunaway.png 

static Qul::Private::RasterBuffer qul_rasterBuffer_icon_5Fthernalrunaway_12523065641773638316 = {
    0xffffffff,
    71,
    60,
    0,
    NULL
};
extern const Qul::Private::RasterBuffer * const qul_rasterBuffer_icon_5Fthernalrunaway_12523065641773638316_handle;
const Qul::Private::RasterBuffer * const qul_rasterBuffer_icon_5Fthernalrunaway_12523065641773638316_handle = &qul_rasterBuffer_icon_5Fthernalrunaway_12523065641773638316;


