// This code is auto-generated by Qul's qulrcc tool.
// WARNING! All changes made in this file will be lost!
#include <qul/private/graphicsdevice.h>


// file path :/assets/1024x600/icon_reverse.png 

static Qul::Private::RasterBuffer qul_rasterBuffer_icon_5Freverse_17416783858259955841 = {
    0xffffffff,
    44,
    44,
    0,
    NULL
};
extern const Qul::Private::RasterBuffer * const qul_rasterBuffer_icon_5Freverse_17416783858259955841_handle;
const Qul::Private::RasterBuffer * const qul_rasterBuffer_icon_5Freverse_17416783858259955841_handle = &qul_rasterBuffer_icon_5Freverse_17416783858259955841;


