// This code is auto-generated by Qul's qulrcc tool.
// WARNING! All changes made in this file will be lost!
#include <qul/private/graphicsdevice.h>


// file path :/assets/1024x600/bg_chargescreen.png 

static Qul::Private::RasterBuffer qul_rasterBuffer_bg_5Fchargescreen_7180676069524712334 = {
    0xffffffff,
    1024,
    600,
    0,
    NULL
};
extern const Qul::Private::RasterBuffer * const qul_rasterBuffer_bg_5Fchargescreen_7180676069524712334_handle;
const Qul::Private::RasterBuffer * const qul_rasterBuffer_bg_5Fchargescreen_7180676069524712334_handle = &qul_rasterBuffer_bg_5Fchargescreen_7180676069524712334;


