// This code is auto-generated by Qul's qulrcc tool.
// WARNING! All changes made in this file will be lost!
#include <qul/private/graphicsdevice.h>


// file path :/assets/1024x600/logo_splashscreen_qucev.png 

static Qul::Private::RasterBuffer qul_rasterBuffer_logo_5Fsplashscreen_5Fqucev_5644429079924280080 = {
    0xffffffff,
    1024,
    600,
    0,
    NULL
};
extern const Qul::Private::RasterBuffer * const qul_rasterBuffer_logo_5Fsplashscreen_5Fqucev_5644429079924280080_handle;
const Qul::Private::RasterBuffer * const qul_rasterBuffer_logo_5Fsplashscreen_5Fqucev_5644429079924280080_handle = &qul_rasterBuffer_logo_5Fsplashscreen_5Fqucev_5644429079924280080;


