// This code is auto-generated by Qul's qulrcc tool.
// WARNING! All changes made in this file will be lost!
#include <qul/private/graphicsdevice.h>


// file path :/assets/1024x600/bg_time.png 

static Qul::Private::RasterBuffer qul_rasterBuffer_bg_5Ftime_9859523829458194445 = {
    0xffffffff,
    212,
    60,
    0,
    NULL
};
extern const Qul::Private::RasterBuffer * const qul_rasterBuffer_bg_5Ftime_9859523829458194445_handle;
const Qul::Private::RasterBuffer * const qul_rasterBuffer_bg_5Ftime_9859523829458194445_handle = &qul_rasterBuffer_bg_5Ftime_9859523829458194445;


