// This code is auto-generated by Qul's qulrcc tool.
// WARNING! All changes made in this file will be lost!
#include <qul/private/graphicsdevice.h>


// file path :/assets/1024x600/icon_lvbatttery.png 

static Qul::Private::RasterBuffer qul_rasterBuffer_icon_5Flvbatttery_17171685252486399335 = {
    0xffffffff,
    50,
    51,
    0,
    NULL
};
extern const Qul::Private::RasterBuffer * const qul_rasterBuffer_icon_5Flvbatttery_17171685252486399335_handle;
const Qul::Private::RasterBuffer * const qul_rasterBuffer_icon_5Flvbatttery_17171685252486399335_handle = &qul_rasterBuffer_icon_5Flvbatttery_17171685252486399335;


