// This code is auto-generated by Qul's qulrcc tool.
// WARNING! All changes made in this file will be lost!
#include <qul/private/graphicsdevice.h>


// file path :/assets/1024x600/icon_breakfault.png 

static Qul::Private::RasterBuffer qul_rasterBuffer_icon_5Fbreakfault_9115011035421616930 = {
    0xffffffff,
    50,
    42,
    0,
    NULL
};
extern const Qul::Private::RasterBuffer * const qul_rasterBuffer_icon_5Fbreakfault_9115011035421616930_handle;
const Qul::Private::RasterBuffer * const qul_rasterBuffer_icon_5Fbreakfault_9115011035421616930_handle = &qul_rasterBuffer_icon_5Fbreakfault_9115011035421616930;


