// This code is auto-generated by Qul's qulrcc tool.
// WARNING! All changes made in this file will be lost!
#include <qul/private/graphicsdevice.h>


// file path :/assets/1024x600/icon_chargefailed.png 

static Qul::Private::RasterBuffer qul_rasterBuffer_icon_5Fchargefailed_12716291351144963468 = {
    0xffffffff,
    206,
    87,
    0,
    NULL
};
extern const Qul::Private::RasterBuffer * const qul_rasterBuffer_icon_5Fchargefailed_12716291351144963468_handle;
const Qul::Private::RasterBuffer * const qul_rasterBuffer_icon_5Fchargefailed_12716291351144963468_handle = &qul_rasterBuffer_icon_5Fchargefailed_12716291351144963468;


