// This code is auto-generated by Qul's qulrcc tool.
// WARNING! All changes made in this file will be lost!
#include <qul/private/graphicsdevice.h>


// file path :/assets/1024x600/icon_parking.png 

static Qul::Private::RasterBuffer qul_rasterBuffer_icon_5Fparking_6386686232902088265 = {
    0xffffffff,
    50,
    39,
    0,
    NULL
};
extern const Qul::Private::RasterBuffer * const qul_rasterBuffer_icon_5Fparking_6386686232902088265_handle;
const Qul::Private::RasterBuffer * const qul_rasterBuffer_icon_5Fparking_6386686232902088265_handle = &qul_rasterBuffer_icon_5Fparking_6386686232902088265;


