// This code is auto-generated by Qul's qulrcc tool.
// WARNING! All changes made in this file will be lost!
#include <qul/private/graphicsdevice.h>


// file path :/assets/1024x600/icon_charging.png 

static Qul::Private::RasterBuffer qul_rasterBuffer_icon_5Fcharging_686463812630201286 = {
    0xffffffff,
    206,
    87,
    0,
    NULL
};
extern const Qul::Private::RasterBuffer * const qul_rasterBuffer_icon_5Fcharging_686463812630201286_handle;
const Qul::Private::RasterBuffer * const qul_rasterBuffer_icon_5Fcharging_686463812630201286_handle = &qul_rasterBuffer_icon_5Fcharging_686463812630201286;


