// This code is auto-generated by Qul's qulrcc tool.
// WARNING! All changes made in this file will be lost!
#include <qul/private/graphicsdevice.h>


// file path :/assets/1024x600/icon_hvbattery.png 

static Qul::Private::RasterBuffer qul_rasterBuffer_icon_5Fhvbattery_556526678156632720 = {
    0xffffffff,
    51,
    50,
    0,
    NULL
};
extern const Qul::Private::RasterBuffer * const qul_rasterBuffer_icon_5Fhvbattery_556526678156632720_handle;
const Qul::Private::RasterBuffer * const qul_rasterBuffer_icon_5Fhvbattery_556526678156632720_handle = &qul_rasterBuffer_icon_5Fhvbattery_556526678156632720;


