// This code is auto-generated by Qul's qulrcc tool.
// WARNING! All changes made in this file will be lost!
#include <qul/private/graphicsdevice.h>


// file path :/assets/1024x600/icon_regen.png 

static Qul::Private::RasterBuffer qul_rasterBuffer_icon_5Fregen_1144791132985929346 = {
    0xffffffff,
    100,
    100,
    0,
    NULL
};
extern const Qul::Private::RasterBuffer * const qul_rasterBuffer_icon_5Fregen_1144791132985929346_handle;
const Qul::Private::RasterBuffer * const qul_rasterBuffer_icon_5Fregen_1144791132985929346_handle = &qul_rasterBuffer_icon_5Fregen_1144791132985929346;


