// This code is auto-generated by Qul's qulrcc tool.
// WARNING! All changes made in this file will be lost!
#include <qul/private/graphicsdevice.h>


// file path :/assets/1024x600/icon_seatbelt.png 

static Qul::Private::RasterBuffer qul_rasterBuffer_icon_5Fseatbelt_3539755803749815478 = {
    0xffffffff,
    60,
    45,
    0,
    NULL
};
extern const Qul::Private::RasterBuffer * const qul_rasterBuffer_icon_5Fseatbelt_3539755803749815478_handle;
const Qul::Private::RasterBuffer * const qul_rasterBuffer_icon_5Fseatbelt_3539755803749815478_handle = &qul_rasterBuffer_icon_5Fseatbelt_3539755803749815478;


