// This code is auto-generated by Qul's qulrcc tool.
// WARNING! All changes made in this file will be lost!

#include <qul/private/qulrcc_lookup.h>

extern const Qul::Private::RasterBuffer *const qul_rasterBuffer_bg_5Ftime_9859523829458194445_handle;
extern const Qul::Private::RasterBuffer *const qul_rasterBuffer_bg_5Fdate_11782441521708933717_handle;
extern const Qul::Private::RasterBuffer *const qul_rasterBuffer_bg_5Frange_5054703357876000134_handle;
extern const Qul::Private::RasterBuffer *const qul_rasterBuffer_icon_5Fsport_12188040122751549104_handle;
extern const Qul::Private::RasterBuffer *const qul_rasterBuffer_logo_5Fqucev_5875142839659060269_handle;
extern const Qul::Private::RasterBuffer *const qul_rasterBuffer_bg_5Fbattery_18233697090329415576_handle;
extern const Qul::Private::RasterBuffer *const qul_rasterBuffer_icon_5Fdrive_13663725601868292502_handle;
extern const Qul::Private::RasterBuffer *const qul_rasterBuffer_icon_5Fregen_1144791132985929346_handle;
extern const Qul::Private::RasterBuffer *const qul_rasterBuffer_console_5Ftop_16956650710360509650_handle;
extern const Qul::Private::RasterBuffer *const qul_rasterBuffer_icon_5Fairbag_3645947267865513010_handle;
extern const Qul::Private::RasterBuffer *const qul_rasterBuffer_icon_5Fneutral_11758454277432732924_handle;
extern const Qul::Private::RasterBuffer *const qul_rasterBuffer_icon_5Flowbeam_4238623879086857656_handle;
extern const Qul::Private::RasterBuffer *const qul_rasterBuffer_icon_5Fparking_6386686232902088265_handle;
extern const Qul::Private::RasterBuffer *const qul_rasterBuffer_icon_5Freverse_17416783858259955841_handle;
extern const Qul::Private::RasterBuffer *const qul_rasterBuffer_icon_5Ffoglight_528535705063815764_handle;
extern const Qul::Private::RasterBuffer *const qul_rasterBuffer_icon_5Flimphome_2074430016763099219_handle;
extern const Qul::Private::RasterBuffer *const qul_rasterBuffer_icon_5Fbmsfault_7493962208881856990_handle;
extern const Qul::Private::RasterBuffer *const qul_rasterBuffer_icon_5Ftempunit_6406722246781797442_handle;
extern const Qul::Private::RasterBuffer *const qul_rasterBuffer_icon_5Fcharging_686463812630201286_handle;
extern const Qul::Private::RasterBuffer *const qul_rasterBuffer_icon_5Fdooropen_7403357616312972229_handle;
extern const Qul::Private::RasterBuffer *const qul_rasterBuffer_icon_5Fhillhold_9436492525155914948_handle;
extern const Qul::Private::RasterBuffer *const qul_rasterBuffer_icon_5Fmaxspeed_8254468392654897759_handle;
extern const Qul::Private::RasterBuffer *const qul_rasterBuffer_icon_5Fseatbelt_3539755803749815478_handle;
extern const Qul::Private::RasterBuffer *const qul_rasterBuffer_icon_5Fhighbeam_1719669687734742552_handle;
extern const Qul::Private::RasterBuffer *const qul_rasterBuffer_icon_5Femptysoc_15574986121963761983_handle;
extern const Qul::Private::RasterBuffer *const qul_rasterBuffer_icon_5Ftruck_5Fred_5066367419100772695_handle;
extern const Qul::Private::RasterBuffer *const qul_rasterBuffer_console_5Fbottom_11656608417757482220_handle;
extern const Qul::Private::RasterBuffer *const qul_rasterBuffer_icon_5Fhvbattery_556526678156632720_handle;
extern const Qul::Private::RasterBuffer *const qul_rasterBuffer_icon_5Fbreakfault_9115011035421616930_handle;
extern const Qul::Private::RasterBuffer *const qul_rasterBuffer_icon_5Flowcoolant_6981526498510333888_handle;
extern const Qul::Private::RasterBuffer *const qul_rasterBuffer_bg_5Fchargescreen_7180676069524712334_handle;
extern const Qul::Private::RasterBuffer *const qul_rasterBuffer_icon_5Flvbatttery_17171685252486399335_handle;
extern const Qul::Private::RasterBuffer *const qul_rasterBuffer_icon_5Fcoolanttemp_13764094077854101002_handle;
extern const Qul::Private::RasterBuffer *const qul_rasterBuffer_icon_5Ftruck_5Fgreen_6354410731505874125_handle;
extern const Qul::Private::RasterBuffer *const qul_rasterBuffer_icon_5Fchargefailed_12716291351144963468_handle;
extern const Qul::Private::RasterBuffer *const qul_rasterBuffer_icon_5Findicatorleft_11280704117166167349_handle;
extern const Qul::Private::RasterBuffer *const qul_rasterBuffer_icon_5Fbatlowcoolant_2173305881106335156_handle;
extern const Qul::Private::RasterBuffer *const qul_rasterBuffer_icon_5Findicatorright_16367534964096713469_handle;
extern const Qul::Private::RasterBuffer *const qul_rasterBuffer_icon_5Fthernalrunaway_12523065641773638316_handle;
extern const Qul::Private::RasterBuffer *const qul_rasterBuffer_icon_5Fchargecomplete_2608203785245619604_handle;
extern const Qul::Private::RasterBuffer *const qul_rasterBuffer_icon_5Fpositionlights_12321207247164481823_handle;
extern const Qul::Private::RasterBuffer *const qul_rasterBuffer_icon_5Fhvbatteryfault_5515237330446869620_handle;
extern const Qul::Private::RasterBuffer *const qul_rasterBuffer_icon_5Fsteeringfailure_5014822368191755891_handle;
extern const Qul::Private::RasterBuffer *const qul_rasterBuffer_icon_5Fsteeringworking_9269225029557674249_handle;
extern const Qul::Private::RasterBuffer *const qul_rasterBuffer_icon_5Fservicedisconnect_7092547091065046762_handle;
extern const Qul::Private::RasterBuffer *const qul_rasterBuffer_logo_5Fsplashscreen_5Fqucev_5644429079924280080_handle;


namespace Qul {
namespace Private {

const ImageAssetLookupEntry qrcImageLookupSize[] = {
    {27, 0, 1},
    {28, 2, 2},
    {30, 3, 7},
    {31, 8, 9},
    {32, 10, 13},
    {33, 14, 24},
    {34, 25, 27},
    {35, 28, 31},
    {36, 32, 33},
    {37, 34, 34},
    {38, 35, 36},
    {39, 37, 41},
    {40, 42, 43},
    {42, 44, 44},
    {43, 45, 45},
    {0, 0, 0}
};

const ImageAssetLookupEntry qrcImageLookupHash[] = {
    {21143, 0, 65535},
    {40502, 1, 65535},
    {51453, 2, 65535},
    {9510, 3, 65535},
    {10264, 4, 65535},
    {18063, 5, 65535},
    {46432, 6, 65535},
    {59063, 7, 65535},
    {20891, 8, 65535},
    {64306, 9, 65535},
    {24633, 10, 65535},
    {48883, 11, 65535},
    {48996, 12, 65535},
    {49996, 13, 65535},
    {5564, 14, 65535},
    {6395, 15, 65535},
    {7738, 16, 65535},
    {7814, 17, 65535},
    {14995, 18, 65535},
    {15758, 19, 65535},
    {19106, 20, 65535},
    {24063, 21, 65535},
    {47472, 22, 65535},
    {57449, 23, 65535},
    {60102, 24, 65535},
    {9019, 25, 65535},
    {10079, 26, 65535},
    {13855, 27, 65535},
    {33497, 28, 65535},
    {40620, 29, 65535},
    {52948, 30, 65535},
    {59567, 31, 65535},
    {8500, 32, 65535},
    {23155, 33, 65535},
    {4501, 34, 65535},
    {5142, 35, 65535},
    {65051, 36, 65535},
    {5069, 37, 65535},
    {44003, 38, 65535},
    {45151, 39, 65535},
    {54936, 40, 65535},
    {57173, 41, 65535},
    {16889, 42, 65535},
    {57880, 43, 65535},
    {3601, 44, 65535},
    {59934, 45, 65535},
    {0, 0, 0}
};

const RasterBuffer *const qrcImageLookupDirect[] = {
    qul_rasterBuffer_bg_5Ftime_9859523829458194445_handle,
    qul_rasterBuffer_bg_5Fdate_11782441521708933717_handle,
    qul_rasterBuffer_bg_5Frange_5054703357876000134_handle,
    qul_rasterBuffer_icon_5Fsport_12188040122751549104_handle,
    qul_rasterBuffer_logo_5Fqucev_5875142839659060269_handle,
    qul_rasterBuffer_bg_5Fbattery_18233697090329415576_handle,
    qul_rasterBuffer_icon_5Fdrive_13663725601868292502_handle,
    qul_rasterBuffer_icon_5Fregen_1144791132985929346_handle,
    qul_rasterBuffer_console_5Ftop_16956650710360509650_handle,
    qul_rasterBuffer_icon_5Fairbag_3645947267865513010_handle,
    qul_rasterBuffer_icon_5Fneutral_11758454277432732924_handle,
    qul_rasterBuffer_icon_5Flowbeam_4238623879086857656_handle,
    qul_rasterBuffer_icon_5Fparking_6386686232902088265_handle,
    qul_rasterBuffer_icon_5Freverse_17416783858259955841_handle,
    qul_rasterBuffer_icon_5Ffoglight_528535705063815764_handle,
    qul_rasterBuffer_icon_5Flimphome_2074430016763099219_handle,
    qul_rasterBuffer_icon_5Fbmsfault_7493962208881856990_handle,
    qul_rasterBuffer_icon_5Ftempunit_6406722246781797442_handle,
    qul_rasterBuffer_icon_5Fcharging_686463812630201286_handle,
    qul_rasterBuffer_icon_5Fdooropen_7403357616312972229_handle,
    qul_rasterBuffer_icon_5Fhillhold_9436492525155914948_handle,
    qul_rasterBuffer_icon_5Fmaxspeed_8254468392654897759_handle,
    qul_rasterBuffer_icon_5Fseatbelt_3539755803749815478_handle,
    qul_rasterBuffer_icon_5Fhighbeam_1719669687734742552_handle,
    qul_rasterBuffer_icon_5Femptysoc_15574986121963761983_handle,
    qul_rasterBuffer_icon_5Ftruck_5Fred_5066367419100772695_handle,
    qul_rasterBuffer_console_5Fbottom_11656608417757482220_handle,
    qul_rasterBuffer_icon_5Fhvbattery_556526678156632720_handle,
    qul_rasterBuffer_icon_5Fbreakfault_9115011035421616930_handle,
    qul_rasterBuffer_icon_5Flowcoolant_6981526498510333888_handle,
    qul_rasterBuffer_bg_5Fchargescreen_7180676069524712334_handle,
    qul_rasterBuffer_icon_5Flvbatttery_17171685252486399335_handle,
    qul_rasterBuffer_icon_5Fcoolanttemp_13764094077854101002_handle,
    qul_rasterBuffer_icon_5Ftruck_5Fgreen_6354410731505874125_handle,
    qul_rasterBuffer_icon_5Fchargefailed_12716291351144963468_handle,
    qul_rasterBuffer_icon_5Findicatorleft_11280704117166167349_handle,
    qul_rasterBuffer_icon_5Fbatlowcoolant_2173305881106335156_handle,
    qul_rasterBuffer_icon_5Findicatorright_16367534964096713469_handle,
    qul_rasterBuffer_icon_5Fthernalrunaway_12523065641773638316_handle,
    qul_rasterBuffer_icon_5Fchargecomplete_2608203785245619604_handle,
    qul_rasterBuffer_icon_5Fpositionlights_12321207247164481823_handle,
    qul_rasterBuffer_icon_5Fhvbatteryfault_5515237330446869620_handle,
    qul_rasterBuffer_icon_5Fsteeringfailure_5014822368191755891_handle,
    qul_rasterBuffer_icon_5Fsteeringworking_9269225029557674249_handle,
    qul_rasterBuffer_icon_5Fservicedisconnect_7092547091065046762_handle,
    qul_rasterBuffer_logo_5Fsplashscreen_5Fqucev_5644429079924280080_handle,
    NULL
};

const quint16 qrcImageLookupSizeLength = 15;


} // namespace Private
} // namespace Qul
