// This code is auto-generated by Qul's qulrcc tool.
// WARNING! All changes made in this file will be lost!
#include <qul/private/graphicsdevice.h>


// file path :/assets/1024x600/bg_light_charge_blue.png 

static Qul::Private::RasterBuffer qul_rasterBuffer_bg_5Flight_5Fcharge_5Fblue_16831047445036315738 = {
    0xffffffff,
    418,
    373,
    0,
    NULL
};
extern const Qul::Private::RasterBuffer * const qul_rasterBuffer_bg_5Flight_5Fcharge_5Fblue_16831047445036315738_handle;
const Qul::Private::RasterBuffer * const qul_rasterBuffer_bg_5Flight_5Fcharge_5Fblue_16831047445036315738_handle = &qul_rasterBuffer_bg_5Flight_5Fcharge_5Fblue_16831047445036315738;


