// This code is auto-generated by Qul's qulrcc tool.
// WARNING! All changes made in this file will be lost!
#include <qul/private/graphicsdevice.h>


// file path :/assets/1024x600/bg_light_ring_green.png 

static Qul::Private::RasterBuffer qul_rasterBuffer_bg_5Flight_5Fring_5Fgreen_5497126269234903875 = {
    0xffffffff,
    291,
    291,
    0,
    NULL
};
extern const Qul::Private::RasterBuffer * const qul_rasterBuffer_bg_5Flight_5Fring_5Fgreen_5497126269234903875_handle;
const Qul::Private::RasterBuffer * const qul_rasterBuffer_bg_5Flight_5Fring_5Fgreen_5497126269234903875_handle = &qul_rasterBuffer_bg_5Flight_5Fring_5Fgreen_5497126269234903875;


