// This code is auto-generated by Qul's qulrcc tool.
// WARNING! All changes made in this file will be lost!
#include <qul/private/graphicsdevice.h>


// file path :/assets/1024x600/icon_motormalfun.png 

static Qul::Private::RasterBuffer qul_rasterBuffer_icon_5Fmotormalfun_6794933055433336268 = {
    0xffffffff,
    45,
    34,
    0,
    NULL
};
extern const Qul::Private::RasterBuffer * const qul_rasterBuffer_icon_5Fmotormalfun_6794933055433336268_handle;
const Qul::Private::RasterBuffer * const qul_rasterBuffer_icon_5Fmotormalfun_6794933055433336268_handle = &qul_rasterBuffer_icon_5Fmotormalfun_6794933055433336268;


