// This code is auto-generated by Qul's qulrcc tool.
// WARNING! All changes made in this file will be lost!
#include <qul/private/graphicsdevice.h>


// file path :/assets/1024x600/icon_timebar_green.svg 

static Qul::Private::RasterBuffer qul_rasterBuffer_icon_5Ftimebar_5Fgreen_3424730075918112142 = {
    0xff55b948,
    500,
    500,
    0,
    NULL
};
extern const Qul::Private::RasterBuffer * const qul_rasterBuffer_icon_5Ftimebar_5Fgreen_3424730075918112142_handle;
const Qul::Private::RasterBuffer * const qul_rasterBuffer_icon_5Ftimebar_5Fgreen_3424730075918112142_handle = &qul_rasterBuffer_icon_5Ftimebar_5Fgreen_3424730075918112142;


