// This code is auto-generated by Qul's qulrcc tool.
// WARNING! All changes made in this file will be lost!
#include <qul/private/graphicsdevice.h>


// file path :/assets/1024x600/bg_light_mode.png 

static Qul::Private::RasterBuffer qul_rasterBuffer_bg_5Flight_5Fmode_2490986634729007414 = {
    0xffffffff,
    381,
    83,
    0,
    NULL
};
extern const Qul::Private::RasterBuffer * const qul_rasterBuffer_bg_5Flight_5Fmode_2490986634729007414_handle;
const Qul::Private::RasterBuffer * const qul_rasterBuffer_bg_5Flight_5Fmode_2490986634729007414_handle = &qul_rasterBuffer_bg_5Flight_5Fmode_2490986634729007414;


