// This code is auto-generated by Qul's qulrcc tool.
// WARNING! All changes made in this file will be lost!
#include <qul/private/graphicsdevice.h>


// file path :/assets/1024x600/icon_coolent.png 

static Qul::Private::RasterBuffer qul_rasterBuffer_icon_5Fcoolent_8965237090492372370 = {
    0xffffffff,
    90,
    60,
    0,
    NULL
};
extern const Qul::Private::RasterBuffer * const qul_rasterBuffer_icon_5Fcoolent_8965237090492372370_handle;
const Qul::Private::RasterBuffer * const qul_rasterBuffer_icon_5Fcoolent_8965237090492372370_handle = &qul_rasterBuffer_icon_5Fcoolent_8965237090492372370;


