// This code is auto-generated by Qul's qulrcc tool.
// WARNING! All changes made in this file will be lost!
#include <qul/private/graphicsdevice.h>


// file path :/assets/1024x600/icon_eabs.png 

static Qul::Private::RasterBuffer qul_rasterBuffer_icon_5Feabs_4586739131316601750 = {
    0xffff7e00,
    90,
    60,
    0,
    NULL
};
extern const Qul::Private::RasterBuffer * const qul_rasterBuffer_icon_5Feabs_4586739131316601750_handle;
const Qul::Private::RasterBuffer * const qul_rasterBuffer_icon_5Feabs_4586739131316601750_handle = &qul_rasterBuffer_icon_5Feabs_4586739131316601750;


