// This code is auto-generated by Qul's qulrcc tool.
// WARNING! All changes made in this file will be lost!
#include <qul/private/graphicsdevice.h>


// file path :/assets/1024x600/icon_hvil.png 

static Qul::Private::RasterBuffer qul_rasterBuffer_icon_5Fhvil_8301420484188515714 = {
    0xffffffff,
    50,
    44,
    0,
    NULL
};
extern const Qul::Private::RasterBuffer * const qul_rasterBuffer_icon_5Fhvil_8301420484188515714_handle;
const Qul::Private::RasterBuffer * const qul_rasterBuffer_icon_5Fhvil_8301420484188515714_handle = &qul_rasterBuffer_icon_5Fhvil_8301420484188515714;


