// This code is auto-generated by Qul's qulrcc tool.
// WARNING! All changes made in this file will be lost!
#include <qul/private/graphicsdevice.h>


// file path :/assets/1024x600/bg_light_speed.png 

static Qul::Private::RasterBuffer qul_rasterBuffer_bg_5Flight_5Fspeed_13090697642961798291 = {
    0xffffffff,
    418,
    358,
    0,
    NULL
};
extern const Qul::Private::RasterBuffer * const qul_rasterBuffer_bg_5Flight_5Fspeed_13090697642961798291_handle;
const Qul::Private::RasterBuffer * const qul_rasterBuffer_bg_5Flight_5Fspeed_13090697642961798291_handle = &qul_rasterBuffer_bg_5Flight_5Fspeed_13090697642961798291;


