// This code is auto-generated by Qul's qulrcc tool.
// WARNING! All changes made in this file will be lost!
#include <qul/private/graphicsdevice.h>


// file path :/assets/1024x600/icon_dark_sel0.png 

static Qul::Private::RasterBuffer qul_rasterBuffer_icon_5Fdark_5Fsel0_3618032118870097789 = {
    0xffffffff,
    40,
    80,
    0,
    NULL
};
extern const Qul::Private::RasterBuffer * const qul_rasterBuffer_icon_5Fdark_5Fsel0_3618032118870097789_handle;
const Qul::Private::RasterBuffer * const qul_rasterBuffer_icon_5Fdark_5Fsel0_3618032118870097789_handle = &qul_rasterBuffer_icon_5Fdark_5Fsel0_3618032118870097789;


