// This code is auto-generated by Qul's qulrcc tool.
// WARNING! All changes made in this file will be lost!
#include <qul/private/graphicsdevice.h>


// file path :/assets/1024x600/bg_light_fault_yellow.png 

static Qul::Private::RasterBuffer qul_rasterBuffer_bg_5Flight_5Ffault_5Fyellow_6874303195522552643 = {
    0xffffffff,
    418,
    365,
    0,
    NULL
};
extern const Qul::Private::RasterBuffer * const qul_rasterBuffer_bg_5Flight_5Ffault_5Fyellow_6874303195522552643_handle;
const Qul::Private::RasterBuffer * const qul_rasterBuffer_bg_5Flight_5Ffault_5Fyellow_6874303195522552643_handle = &qul_rasterBuffer_bg_5Flight_5Ffault_5Fyellow_6874303195522552643;


