// This code is auto-generated by Qul's qulrcc tool.
// WARNING! All changes made in this file will be lost!
#include <qul/private/graphicsdevice.h>


// file path :/assets/1024x600/bg_light_main.png 

static Qul::Private::RasterBuffer qul_rasterBuffer_bg_5Flight_5Fmain_2063180190131945813 = {
    0xffffffff,
    1024,
    600,
    0,
    NULL
};
extern const Qul::Private::RasterBuffer * const qul_rasterBuffer_bg_5Flight_5Fmain_2063180190131945813_handle;
const Qul::Private::RasterBuffer * const qul_rasterBuffer_bg_5Flight_5Fmain_2063180190131945813_handle = &qul_rasterBuffer_bg_5Flight_5Fmain_2063180190131945813;


