// This code is auto-generated by Qul's qulrcc tool.
// WARNING! All changes made in this file will be lost!
#include <qul/private/graphicsdevice.h>


// file path :/assets/1024x600/icon_highbeam.png 

static Qul::Private::RasterBuffer qul_rasterBuffer_icon_5Fhighbeam_1719669687734742552 = {
    0xff0034ff,
    90,
    60,
    0,
    NULL
};
extern const Qul::Private::RasterBuffer * const qul_rasterBuffer_icon_5Fhighbeam_1719669687734742552_handle;
const Qul::Private::RasterBuffer * const qul_rasterBuffer_icon_5Fhighbeam_1719669687734742552_handle = &qul_rasterBuffer_icon_5Fhighbeam_1719669687734742552;


