// This code is auto-generated by Qul's qulrcc tool.
// WARNING! All changes made in this file will be lost!
#include <qul/private/graphicsdevice.h>


// file path :/assets/1024x600/bg_dark_green.png 

static Qul::Private::RasterBuffer qul_rasterBuffer_bg_5Fdark_5Fgreen_9690728259582573138 = {
    0xffffffff,
    418,
    375,
    0,
    NULL
};
extern const Qul::Private::RasterBuffer * const qul_rasterBuffer_bg_5Fdark_5Fgreen_9690728259582573138_handle;
const Qul::Private::RasterBuffer * const qul_rasterBuffer_bg_5Fdark_5Fgreen_9690728259582573138_handle = &qul_rasterBuffer_bg_5Fdark_5Fgreen_9690728259582573138;


