// This code is auto-generated by Qul's qulrcc tool.
// WARNING! All changes made in this file will be lost!
#include <qul/private/graphicsdevice.h>


// file path :/assets/1024x600/icon_light_sel1.png 

static Qul::Private::RasterBuffer qul_rasterBuffer_icon_5Flight_5Fsel1_12672939284137474243 = {
    0xffffffff,
    40,
    80,
    0,
    NULL
};
extern const Qul::Private::RasterBuffer * const qul_rasterBuffer_icon_5Flight_5Fsel1_12672939284137474243_handle;
const Qul::Private::RasterBuffer * const qul_rasterBuffer_icon_5Flight_5Fsel1_12672939284137474243_handle = &qul_rasterBuffer_icon_5Flight_5Fsel1_12672939284137474243;


