// This code is auto-generated by Qul's qulrcc tool.
// WARNING! All changes made in this file will be lost!
#include <qul/private/graphicsdevice.h>


// file path :/assets/1024x600/icon_foglight.png 

static Qul::Private::RasterBuffer qul_rasterBuffer_icon_5Ffoglight_528535705063815764 = {
    0xffffffff,
    50,
    50,
    0,
    NULL
};
extern const Qul::Private::RasterBuffer * const qul_rasterBuffer_icon_5Ffoglight_528535705063815764_handle;
const Qul::Private::RasterBuffer * const qul_rasterBuffer_icon_5Ffoglight_528535705063815764_handle = &qul_rasterBuffer_icon_5Ffoglight_528535705063815764;


