// This code is auto-generated by Qul's qulrcc tool.
// WARNING! All changes made in this file will be lost!
#include <qul/private/graphicsdevice.h>


// file path :/assets/1024x600/icon_batteryfailure.png 

static Qul::Private::RasterBuffer qul_rasterBuffer_icon_5Fbatteryfailure_8857017888184466976 = {
    0xffffffff,
    50,
    39,
    0,
    NULL
};
extern const Qul::Private::RasterBuffer * const qul_rasterBuffer_icon_5Fbatteryfailure_8857017888184466976_handle;
const Qul::Private::RasterBuffer * const qul_rasterBuffer_icon_5Fbatteryfailure_8857017888184466976_handle = &qul_rasterBuffer_icon_5Fbatteryfailure_8857017888184466976;


