// This code is auto-generated by Qul's qulrcc tool.
// WARNING! All changes made in this file will be lost!
#include <qul/private/graphicsdevice.h>


// file path :/assets/1024x600/bg_dark_fault_yellow.png 

static Qul::Private::RasterBuffer qul_rasterBuffer_bg_5Fdark_5Ffault_5Fyellow_7871725417570526092 = {
    0xffffffff,
    418,
    375,
    0,
    NULL
};
extern const Qul::Private::RasterBuffer * const qul_rasterBuffer_bg_5Fdark_5Ffault_5Fyellow_7871725417570526092_handle;
const Qul::Private::RasterBuffer * const qul_rasterBuffer_bg_5Fdark_5Ffault_5Fyellow_7871725417570526092_handle = &qul_rasterBuffer_bg_5Fdark_5Ffault_5Fyellow_7871725417570526092;


