// This code is auto-generated by Qul's qulrcc tool.
// WARNING! All changes made in this file will be lost!
#include <qul/private/graphicsdevice.h>


// file path :/assets/1024x600/icon_breakfailed.png 

static Qul::Private::RasterBuffer qul_rasterBuffer_icon_5Fbreakfailed_9978985468916230188 = {
    0xffffffff,
    50,
    42,
    0,
    NULL
};
extern const Qul::Private::RasterBuffer * const qul_rasterBuffer_icon_5Fbreakfailed_9978985468916230188_handle;
const Qul::Private::RasterBuffer * const qul_rasterBuffer_icon_5Fbreakfailed_9978985468916230188_handle = &qul_rasterBuffer_icon_5Fbreakfailed_9978985468916230188;


