// This code is auto-generated by Qul's qulrcc tool.
// WARNING! All changes made in this file will be lost!
#include <qul/private/graphicsdevice.h>


// file path :/assets/1024x600/icon_dark_sel1.png 

static Qul::Private::RasterBuffer qul_rasterBuffer_icon_5Fdark_5Fsel1_8972954664291827559 = {
    0xffffffff,
    40,
    80,
    0,
    NULL
};
extern const Qul::Private::RasterBuffer * const qul_rasterBuffer_icon_5Fdark_5Fsel1_8972954664291827559_handle;
const Qul::Private::RasterBuffer * const qul_rasterBuffer_icon_5Fdark_5Fsel1_8972954664291827559_handle = &qul_rasterBuffer_icon_5Fdark_5Fsel1_8972954664291827559;


