// This code is auto-generated by Qul's qulrcc tool.
// WARNING! All changes made in this file will be lost!
#include <qul/private/graphicsdevice.h>


// file path :/assets/1024x600/icon_hazard.png 

static Qul::Private::RasterBuffer qul_rasterBuffer_icon_5Fhazard_16444777003624801327 = {
    0xffffffff,
    45,
    40,
    0,
    NULL
};
extern const Qul::Private::RasterBuffer * const qul_rasterBuffer_icon_5Fhazard_16444777003624801327_handle;
const Qul::Private::RasterBuffer * const qul_rasterBuffer_icon_5Fhazard_16444777003624801327_handle = &qul_rasterBuffer_icon_5Fhazard_16444777003624801327;


