// This code is auto-generated by Qul's qulrcc tool.
// WARNING! All changes made in this file will be lost!
#include <qul/private/graphicsdevice.h>


// file path :/assets/1024x600/bg_dark_speed.png 

static Qul::Private::RasterBuffer qul_rasterBuffer_bg_5Fdark_5Fspeed_8900206339527240340 = {
    0xffffffff,
    418,
    351,
    0,
    NULL
};
extern const Qul::Private::RasterBuffer * const qul_rasterBuffer_bg_5Fdark_5Fspeed_8900206339527240340_handle;
const Qul::Private::RasterBuffer * const qul_rasterBuffer_bg_5Fdark_5Fspeed_8900206339527240340_handle = &qul_rasterBuffer_bg_5Fdark_5Fspeed_8900206339527240340;


