// This code is auto-generated by Qul's qulrcc tool.
// WARNING! All changes made in this file will be lost!
#include <qul/private/graphicsdevice.h>


// file path :/assets/1024x600/bg_dark_charge_blue.png 

static Qul::Private::RasterBuffer qul_rasterBuffer_bg_5Fdark_5Fcharge_5Fblue_8874542188519920752 = {
    0xffffffff,
    418,
    374,
    0,
    NULL
};
extern const Qul::Private::RasterBuffer * const qul_rasterBuffer_bg_5Fdark_5Fcharge_5Fblue_8874542188519920752_handle;
const Qul::Private::RasterBuffer * const qul_rasterBuffer_bg_5Fdark_5Fcharge_5Fblue_8874542188519920752_handle = &qul_rasterBuffer_bg_5Fdark_5Fcharge_5Fblue_8874542188519920752;


