// This code is auto-generated by Qul's qulrcc tool.
// WARNING! All changes made in this file will be lost!
#include <qul/private/graphicsdevice.h>


// file path :/assets/1024x600/icon_light_sel2.png 

static Qul::Private::RasterBuffer qul_rasterBuffer_icon_5Flight_5Fsel2_5227814172742466945 = {
    0xffffffff,
    40,
    80,
    0,
    NULL
};
extern const Qul::Private::RasterBuffer * const qul_rasterBuffer_icon_5Flight_5Fsel2_5227814172742466945_handle;
const Qul::Private::RasterBuffer * const qul_rasterBuffer_icon_5Flight_5Fsel2_5227814172742466945_handle = &qul_rasterBuffer_icon_5Flight_5Fsel2_5227814172742466945;


