// This code is auto-generated by Qul's qulrcc tool.
// WARNING! All changes made in this file will be lost!
#include <qul/private/graphicsdevice.h>


// file path :/assets/1024x600/icon_gunlock.png 

static Qul::Private::RasterBuffer qul_rasterBuffer_icon_5Fgunlock_2496129977020822111 = {
    0xffffffff,
    69,
    49,
    0,
    NULL
};
extern const Qul::Private::RasterBuffer * const qul_rasterBuffer_icon_5Fgunlock_2496129977020822111_handle;
const Qul::Private::RasterBuffer * const qul_rasterBuffer_icon_5Fgunlock_2496129977020822111_handle = &qul_rasterBuffer_icon_5Fgunlock_2496129977020822111;


