// This code is auto-generated by Qul's qulrcc tool.
// WARNING! All changes made in this file will be lost!
#include <qul/private/graphicsdevice.h>


// file path :/assets/1024x600/icon_batterywarning.png 

static Qul::Private::RasterBuffer qul_rasterBuffer_icon_5Fbatterywarning_15221464043060138405 = {
    0xffffffff,
    60,
    32,
    0,
    NULL
};
extern const Qul::Private::RasterBuffer * const qul_rasterBuffer_icon_5Fbatterywarning_15221464043060138405_handle;
const Qul::Private::RasterBuffer * const qul_rasterBuffer_icon_5Fbatterywarning_15221464043060138405_handle = &qul_rasterBuffer_icon_5Fbatterywarning_15221464043060138405;


