// This code is auto-generated by Qul's qulrcc tool.
// WARNING! All changes made in this file will be lost!
#include <qul/private/graphicsdevice.h>


// file path :/assets/1024x600/icon_handbreak.png 

static Qul::Private::RasterBuffer qul_rasterBuffer_icon_5Fhandbreak_11812009499601886511 = {
    0xffffffff,
    50,
    39,
    0,
    NULL
};
extern const Qul::Private::RasterBuffer * const qul_rasterBuffer_icon_5Fhandbreak_11812009499601886511_handle;
const Qul::Private::RasterBuffer * const qul_rasterBuffer_icon_5Fhandbreak_11812009499601886511_handle = &qul_rasterBuffer_icon_5Fhandbreak_11812009499601886511;


