// This code is auto-generated by Qul's qulrcc tool.
// WARNING! All changes made in this file will be lost!
#include <qul/private/graphicsdevice.h>


// file path :/assets/1024x600/bg_light_green.png 

static Qul::Private::RasterBuffer qul_rasterBuffer_bg_5Flight_5Fgreen_13604947674073245280 = {
    0xffffffff,
    418,
    365,
    0,
    NULL
};
extern const Qul::Private::RasterBuffer * const qul_rasterBuffer_bg_5Flight_5Fgreen_13604947674073245280_handle;
const Qul::Private::RasterBuffer * const qul_rasterBuffer_bg_5Flight_5Fgreen_13604947674073245280_handle = &qul_rasterBuffer_bg_5Flight_5Fgreen_13604947674073245280;


