// This code is auto-generated by Qul's qulrcc tool.
// WARNING! All changes made in this file will be lost!
#include <qul/private/graphicsdevice.h>


// file path :/assets/1024x600/bg_light_ring_red.png 

static Qul::Private::RasterBuffer qul_rasterBuffer_bg_5Flight_5Fring_5Fred_16037564956433745116 = {
    0xffffffff,
    291,
    291,
    0,
    NULL
};
extern const Qul::Private::RasterBuffer * const qul_rasterBuffer_bg_5Flight_5Fring_5Fred_16037564956433745116_handle;
const Qul::Private::RasterBuffer * const qul_rasterBuffer_bg_5Flight_5Fring_5Fred_16037564956433745116_handle = &qul_rasterBuffer_bg_5Flight_5Fring_5Fred_16037564956433745116;


