// This code is auto-generated by Qul's qulrcc tool.
// WARNING! All changes made in this file will be lost!
#include <qul/private/graphicsdevice.h>


// file path :/assets/1024x600/bg_dark_ring_green.png 

static Qul::Private::RasterBuffer qul_rasterBuffer_bg_5Fdark_5Fring_5Fgreen_1894783914989045776 = {
    0xffffffff,
    291,
    291,
    0,
    NULL
};
extern const Qul::Private::RasterBuffer * const qul_rasterBuffer_bg_5Fdark_5Fring_5Fgreen_1894783914989045776_handle;
const Qul::Private::RasterBuffer * const qul_rasterBuffer_bg_5Fdark_5Fring_5Fgreen_1894783914989045776_handle = &qul_rasterBuffer_bg_5Fdark_5Fring_5Fgreen_1894783914989045776;


