// This code is auto-generated by Qul's qulrcc tool.
// WARNING! All changes made in this file will be lost!

#include <qul/private/qulrcc_lookup.h>

extern const Qul::Private::RasterBuffer *const qul_rasterBuffer_bg_5Fsplash_3284188603857149310_handle;
extern const Qul::Private::RasterBuffer *const qul_rasterBuffer_icon_5Feabs_4586739131316601750_handle;
extern const Qul::Private::RasterBuffer *const qul_rasterBuffer_icon_5Fhvil_8301420484188515714_handle;
extern const Qul::Private::RasterBuffer *const qul_rasterBuffer_icon_5Ffault_461058326346938906_handle;
extern const Qul::Private::RasterBuffer *const qul_rasterBuffer_icon_5Fdrive_13663725601868292502_handle;
extern const Qul::Private::RasterBuffer *const qul_rasterBuffer_icon_5Fhazard_16444777003624801327_handle;
extern const Qul::Private::RasterBuffer *const qul_rasterBuffer_bg_5Fdark_5Fmain_3603716216601726774_handle;
extern const Qul::Private::RasterBuffer *const qul_rasterBuffer_icon_5Fneutral_11758454277432732924_handle;
extern const Qul::Private::RasterBuffer *const qul_rasterBuffer_bg_5Fdark_5Fmode_10741302608000416473_handle;
extern const Qul::Private::RasterBuffer *const qul_rasterBuffer_icon_5Fgunlock_2496129977020822111_handle;
extern const Qul::Private::RasterBuffer *const qul_rasterBuffer_icon_5Flowbeam_4238623879086857656_handle;
extern const Qul::Private::RasterBuffer *const qul_rasterBuffer_icon_5Fcoolent_8965237090492372370_handle;
extern const Qul::Private::RasterBuffer *const qul_rasterBuffer_icon_5Freverse_17416783858259955841_handle;
extern const Qul::Private::RasterBuffer *const qul_rasterBuffer_icon_5Ffoglight_528535705063815764_handle;
extern const Qul::Private::RasterBuffer *const qul_rasterBuffer_bg_5Fdark_5Fgreen_9690728259582573138_handle;
extern const Qul::Private::RasterBuffer *const qul_rasterBuffer_bg_5Fdark_5Fspeed_8900206339527240340_handle;
extern const Qul::Private::RasterBuffer *const qul_rasterBuffer_icon_5Fseatbelt_3539755803749815478_handle;
extern const Qul::Private::RasterBuffer *const qul_rasterBuffer_bg_5Flight_5Fmode_2490986634729007414_handle;
extern const Qul::Private::RasterBuffer *const qul_rasterBuffer_icon_5Fhighbeam_1719669687734742552_handle;
extern const Qul::Private::RasterBuffer *const qul_rasterBuffer_bg_5Flight_5Fmain_2063180190131945813_handle;
extern const Qul::Private::RasterBuffer *const qul_rasterBuffer_icon_5Fdark_5Fsel2_5414158481472900161_handle;
extern const Qul::Private::RasterBuffer *const qul_rasterBuffer_icon_5Fdark_5Fsel0_3618032118870097789_handle;
extern const Qul::Private::RasterBuffer *const qul_rasterBuffer_icon_5Fdark_5Fsel1_8972954664291827559_handle;
extern const Qul::Private::RasterBuffer *const qul_rasterBuffer_icon_5Fhandbreak_11812009499601886511_handle;
extern const Qul::Private::RasterBuffer *const qul_rasterBuffer_bg_5Flight_5Fgreen_13604947674073245280_handle;
extern const Qul::Private::RasterBuffer *const qul_rasterBuffer_bg_5Flight_5Fspeed_13090697642961798291_handle;
extern const Qul::Private::RasterBuffer *const qul_rasterBuffer_icon_5Flight_5Fsel1_12672939284137474243_handle;
extern const Qul::Private::RasterBuffer *const qul_rasterBuffer_icon_5Flight_5Fsel0_17660927272431493077_handle;
extern const Qul::Private::RasterBuffer *const qul_rasterBuffer_icon_5Flight_5Fsel2_5227814172742466945_handle;
extern const Qul::Private::RasterBuffer *const qul_rasterBuffer_icon_5Fmotorfault_925797647956377049_handle;
extern const Qul::Private::RasterBuffer *const qul_rasterBuffer_icon_5Ftimebar_5Fred_10581680189072318016_handle;
extern const Qul::Private::RasterBuffer *const qul_rasterBuffer_icon_5Fbreakfailed_9978985468916230188_handle;
extern const Qul::Private::RasterBuffer *const qul_rasterBuffer_bg_5Fdark_5Fring_5Fred_11597768771768360761_handle;
extern const Qul::Private::RasterBuffer *const qul_rasterBuffer_icon_5Fmotormalfun_6794933055433336268_handle;
extern const Qul::Private::RasterBuffer *const qul_rasterBuffer_icon_5Fcoolenttemp_267475776831725821_handle;
extern const Qul::Private::RasterBuffer *const qul_rasterBuffer_bg_5Flight_5Fring_5Fred_16037564956433745116_handle;
extern const Qul::Private::RasterBuffer *const qul_rasterBuffer_icon_5Findicatorleft_11280704117166167349_handle;
extern const Qul::Private::RasterBuffer *const qul_rasterBuffer_bg_5Fdark_5Fring_5Fgreen_1894783914989045776_handle;
extern const Qul::Private::RasterBuffer *const qul_rasterBuffer_icon_5Ftimebar_5Fgreen_3424730075918112142_handle;
extern const Qul::Private::RasterBuffer *const qul_rasterBuffer_icon_5Findicatorright_16367534964096713469_handle;
extern const Qul::Private::RasterBuffer *const qul_rasterBuffer_icon_5Fbatteryfailure_8857017888184466976_handle;
extern const Qul::Private::RasterBuffer *const qul_rasterBuffer_icon_5Fbatterywarning_15221464043060138405_handle;
extern const Qul::Private::RasterBuffer *const qul_rasterBuffer_bg_5Flight_5Fring_5Fgreen_5497126269234903875_handle;
extern const Qul::Private::RasterBuffer *const qul_rasterBuffer_bg_5Fdark_5Fcharge_5Fblue_8874542188519920752_handle;
extern const Qul::Private::RasterBuffer *const qul_rasterBuffer_bg_5Fdark_5Ffault_5Fyellow_7871725417570526092_handle;
extern const Qul::Private::RasterBuffer *const qul_rasterBuffer_bg_5Flight_5Fcharge_5Fblue_16831047445036315738_handle;
extern const Qul::Private::RasterBuffer *const qul_rasterBuffer_bg_5Flight_5Ffault_5Fyellow_6874303195522552643_handle;


namespace Qul {
namespace Private {

const ImageAssetLookupEntry qrcImageLookupSize[] = {
    {29, 0, 2},
    {30, 3, 4},
    {31, 5, 5},
    {32, 6, 12},
    {33, 13, 19},
    {34, 20, 25},
    {35, 26, 29},
    {36, 30, 34},
    {37, 35, 35},
    {38, 36, 38},
    {39, 39, 43},
    {40, 44, 45},
    {41, 46, 46},
    {0, 0, 0}
};

const ImageAssetLookupEntry qrcImageLookupHash[] = {
    {29687, 0, 65535},
    {54937, 1, 65535},
    {55511, 2, 65535},
    {30982, 3, 65535},
    {46432, 4, 65535},
    {39976, 5, 65535},
    {13834, 6, 65535},
    {24633, 7, 65535},
    {32034, 8, 65535},
    {46971, 9, 65535},
    {48883, 10, 65535},
    {49500, 11, 65535},
    {49996, 12, 65535},
    {5564, 13, 65535},
    {13466, 14, 65535},
    {44870, 15, 65535},
    {47472, 16, 65535},
    {57024, 17, 65535},
    {57449, 18, 65535},
    {63784, 19, 65535},
    {1383, 20, 65535},
    {5605, 21, 65535},
    {15972, 22, 65535},
    {19440, 23, 65535},
    {52280, 24, 65535},
    {63844, 25, 65535},
    {25030, 26, 65535},
    {27079, 27, 65535},
    {31301, 28, 65535},
    {33005, 29, 65535},
    {1727, 30, 65535},
    {9936, 31, 65535},
    {45375, 32, 65535},
    {56890, 33, 65535},
    {61744, 34, 65535},
    {52509, 35, 65535},
    {5142, 36, 65535},
    {14711, 37, 65535},
    {20087, 38, 65535},
    {5069, 39, 65535},
    {16897, 40, 65535},
    {30347, 41, 65535},
    {40405, 42, 65535},
    {61530, 43, 65535},
    {1424, 44, 65535},
    {41400, 45, 65535},
    {47218, 46, 65535},
    {0, 0, 0}
};

const RasterBuffer *const qrcImageLookupDirect[] = {
    qul_rasterBuffer_bg_5Fsplash_3284188603857149310_handle,
    qul_rasterBuffer_icon_5Feabs_4586739131316601750_handle,
    qul_rasterBuffer_icon_5Fhvil_8301420484188515714_handle,
    qul_rasterBuffer_icon_5Ffault_461058326346938906_handle,
    qul_rasterBuffer_icon_5Fdrive_13663725601868292502_handle,
    qul_rasterBuffer_icon_5Fhazard_16444777003624801327_handle,
    qul_rasterBuffer_bg_5Fdark_5Fmain_3603716216601726774_handle,
    qul_rasterBuffer_icon_5Fneutral_11758454277432732924_handle,
    qul_rasterBuffer_bg_5Fdark_5Fmode_10741302608000416473_handle,
    qul_rasterBuffer_icon_5Fgunlock_2496129977020822111_handle,
    qul_rasterBuffer_icon_5Flowbeam_4238623879086857656_handle,
    qul_rasterBuffer_icon_5Fcoolent_8965237090492372370_handle,
    qul_rasterBuffer_icon_5Freverse_17416783858259955841_handle,
    qul_rasterBuffer_icon_5Ffoglight_528535705063815764_handle,
    qul_rasterBuffer_bg_5Fdark_5Fgreen_9690728259582573138_handle,
    qul_rasterBuffer_bg_5Fdark_5Fspeed_8900206339527240340_handle,
    qul_rasterBuffer_icon_5Fseatbelt_3539755803749815478_handle,
    qul_rasterBuffer_bg_5Flight_5Fmode_2490986634729007414_handle,
    qul_rasterBuffer_icon_5Fhighbeam_1719669687734742552_handle,
    qul_rasterBuffer_bg_5Flight_5Fmain_2063180190131945813_handle,
    qul_rasterBuffer_icon_5Fdark_5Fsel2_5414158481472900161_handle,
    qul_rasterBuffer_icon_5Fdark_5Fsel0_3618032118870097789_handle,
    qul_rasterBuffer_icon_5Fdark_5Fsel1_8972954664291827559_handle,
    qul_rasterBuffer_icon_5Fhandbreak_11812009499601886511_handle,
    qul_rasterBuffer_bg_5Flight_5Fgreen_13604947674073245280_handle,
    qul_rasterBuffer_bg_5Flight_5Fspeed_13090697642961798291_handle,
    qul_rasterBuffer_icon_5Flight_5Fsel1_12672939284137474243_handle,
    qul_rasterBuffer_icon_5Flight_5Fsel0_17660927272431493077_handle,
    qul_rasterBuffer_icon_5Flight_5Fsel2_5227814172742466945_handle,
    qul_rasterBuffer_icon_5Fmotorfault_925797647956377049_handle,
    qul_rasterBuffer_icon_5Ftimebar_5Fred_10581680189072318016_handle,
    qul_rasterBuffer_icon_5Fbreakfailed_9978985468916230188_handle,
    qul_rasterBuffer_bg_5Fdark_5Fring_5Fred_11597768771768360761_handle,
    qul_rasterBuffer_icon_5Fmotormalfun_6794933055433336268_handle,
    qul_rasterBuffer_icon_5Fcoolenttemp_267475776831725821_handle,
    qul_rasterBuffer_bg_5Flight_5Fring_5Fred_16037564956433745116_handle,
    qul_rasterBuffer_icon_5Findicatorleft_11280704117166167349_handle,
    qul_rasterBuffer_bg_5Fdark_5Fring_5Fgreen_1894783914989045776_handle,
    qul_rasterBuffer_icon_5Ftimebar_5Fgreen_3424730075918112142_handle,
    qul_rasterBuffer_icon_5Findicatorright_16367534964096713469_handle,
    qul_rasterBuffer_icon_5Fbatteryfailure_8857017888184466976_handle,
    qul_rasterBuffer_icon_5Fbatterywarning_15221464043060138405_handle,
    qul_rasterBuffer_bg_5Flight_5Fring_5Fgreen_5497126269234903875_handle,
    qul_rasterBuffer_bg_5Fdark_5Fcharge_5Fblue_8874542188519920752_handle,
    qul_rasterBuffer_bg_5Fdark_5Ffault_5Fyellow_7871725417570526092_handle,
    qul_rasterBuffer_bg_5Flight_5Fcharge_5Fblue_16831047445036315738_handle,
    qul_rasterBuffer_bg_5Flight_5Ffault_5Fyellow_6874303195522552643_handle,
    NULL
};

const quint16 qrcImageLookupSizeLength = 13;


} // namespace Private
} // namespace Qul
