// This code is auto-generated by Qul's qulrcc tool.
// WARNING! All changes made in this file will be lost!

#include <qul/private/qulrcc_runtimeallocation.h>

namespace Qul {
namespace Private {

const quint8 QUL_NUM_RUNTIME_ALLOCATION_TYPES = 1;

const RuntimeAllocationTypeInfo qulRuntimeAllocationTypeInfo[] = {
    {1, 4194304}
};

static ResourceCache qulResourceCache_0(0);

ResourceCache *qulResourceCaches[] = {
    &qulResourceCache_0
};

} // namespace Private
} // namespace Qul
