// This code is auto-generated by Qul's qmlinterfacegenerator tool from file 'C:/user/Automotive/Cluster/Codebase/Xavion/EvCluster/cluster/controller/hmi/inc/hmihandler.h'
// WARNING! All changes made in this file will be lost!

pragma qmlinterface;
pragma Singleton;
pragma cppname$HmiEventQueue;
import "C:/user/Automotive/Cluster/Codebase/Xavion/EvCluster/cluster/controller/hmi/inc/hmihandler.h";
import QtQuick;

Singleton {
    function onEvent(sEvent)  {}
    function onQueueOverrun()  {}
    function onEventDiscarded(event)  {}
}
