// This code is auto-generated by Qul's qmlinterfacegenerator tool from file 'C:/user/Automotive/Cluster/Codebase/Xavion/EvCluster/cluster/controller/hmi/inc/hmihandler.h'
// WARNING! All changes made in this file will be lost!

pragma qmlinterface;
pragma Singleton;
pragma cppname$HmiHandler;
import "C:/user/Automotive/Cluster/Codebase/Xavion/EvCluster/cluster/controller/hmi/inc/hmihandler.h";
import QtQuick;

Singleton {
    enum ClusterEvents_t { Event_None = 0, Event_Motor = 1, Event_Battery = 2, Event_DriveMode = 3, Event_DeviceStatus = 4, Event_Indicator = 5, Event_HwIndicator = 6, Event_Message = 7, Event_Standby = 8, Event_Fault = 9, Event_Call = 10, Event_TurnByTurnNav = 11, Event_NavSwitch = 12, Event_Time = 13, Event_Alert = 14, Event_DeviceInfo = 15, Event_BTMessage = 16, Event_Charge = 17, Event_BMS = 18, Event_Indicator1 = 19, Event_Indicator2 = 20, Event_Indicator3 = 21, Event_Max = 22 }
    signal fault0StatusChanged(int mfault0, int mfault1, int mfault2, int mfault3);
    signal fault1StatusChanged(int mfault0, int mfault1, int mfault2, int mfault3);
    signal fault2StatusChanged(int mfault0, int mfault1, int mfault2, int mfault3);
    signal fault3StatusChanged(int mfault0, int mfault1, int mfault2, int mfault3);
    signal fault4StatusChanged(int mfault0, int mfault1, int mfault2, int mfault3);
    signal dateTimeChanged(int mday, int mmonth, int myear, int mhour, int mminute, bool mPM, int medit, int mstate);
    signal navSwitchStatusChanged(int mkey);
    signal battInfoChanged(int msoc, int mbattemp);
    signal chargerInfoChanged(bool mtype, bool mstatus, bool mgunlock, int mctime);
    signal driveModeChanged(int mdrivemode, int mgearmode);
    signal motorInfoChanged(int mspeed, int mrange, int mtrip, int modo, int mrpm, int mpower, bool mregen);
    signal alertInfoChanged(int mid, int mcode);
    signal statusInfoChanged(bool mbatfault, bool mbatmalfunc, bool mptfault, bool mptmalfunc, bool mhvil, bool mcoolent);
    signal hwStatusChanged(bool mleftind, bool mrightind, bool mhighbeam, bool mlowbeam, bool mhazard, bool mbrakefailed, bool msafetybelt, bool mhandbrake, bool mfoglight);
    signal messageChanged(int mmsgid);
    signal deviceInfoChanged(int mswversion, int mhwversion, int mslnum);
    function updatePlatform(eEvent : int, pEventParam)  {}
    function updateUI(eEvent : int, pEventParam)  {}
}
