// This code is auto-generated by Qul's qmltocpp tool from the file 'hmimain.qml'
// WARNING! All changes made in this file will be lost!
// NOTE: This generated API is to be considered implementation detail for Qul.
//       It may change from version to version and should not be relied upon.
#pragma once
#include "C:/user/Automotive/Cluster/Codebase/Dorleco/EvCluster/cluster/controller/hmi/inc/hmihandler.h"
#include <platforminterface/log.h>
#include <qul/image.h>
#include <qul/private/animation.h>
#include <qul/private/builtins.h>
#include <qul/private/extras/statictext.h>
#include <qul/private/file.h>
#include <qul/private/items.h>
#include <qul/private/items/component.h>
#include <qul/private/items/item.h>
#include <qul/private/items/text.h>
#include <qul/private/qulrcc_lookup.h>
#include <qul/private/timeritem.h>
#include <qul/private/unicodestring.h>
#include <qul/signal.h>


struct hmimain : Qul::Private::Items::Item , public Qul::Private::Items::ItemBase ::ExtraStorage_itemExtraProperties<Qul::Private::Items::Item  > {
    hmimain();


    Qul::Property<Qul::Private::String> state;
    struct speed_anim_NumberAnimation : Qul::Private::Items::NumberAnimation <int> {
    } speed_anim;
    struct soc_anim_NumberAnimation : Qul::Private::Items::NumberAnimation <int> {
    } soc_anim;
    struct timer_Timer : Qul::Private::Items::Timer  {
    } timer;
    struct triptimer_Timer : Qul::Private::Items::Timer  {
    } triptimer;
    struct deviceinfotimer_Timer : Qul::Private::Items::Timer  {
    } deviceinfotimer;
    struct splashlogo_Image : Qul::Private::Items::Image , public Qul::Private::Items::ItemBase ::ExtraStorage_itemExtraProperties<Qul::Private::Items::Image  > {
        splashlogo_Image()
            : Qul::Private::Items::ItemBase ::ExtraStorage_itemExtraProperties<Qul::Private::Items::Image  >(this)
        {}
    } splashlogo;
    struct splashscreen_Rectangle : Qul::Private::Items::Rectangle , public Qul::Private::Items::ItemBase ::ExtraStorage_itemExtraProperties<Qul::Private::Items::Rectangle  > {
        splashscreen_Rectangle()
            : Qul::Private::Items::ItemBase ::ExtraStorage_itemExtraProperties<Qul::Private::Items::Rectangle  >(this)
        {}
    } splashscreen;
    struct logo_Image : Qul::Private::Items::Image , public Qul::Private::Items::ItemBase ::ExtraStorage_itemExtraProperties<Qul::Private::Items::Image  > {
        logo_Image()
            : Qul::Private::Items::ItemBase ::ExtraStorage_itemExtraProperties<Qul::Private::Items::Image  >(this)
        {}
    } logo;
    struct truckgreen_Image : Qul::Private::Items::Image , public Qul::Private::Items::ItemBase ::ExtraStorage_itemExtraProperties<Qul::Private::Items::Image  > {
        truckgreen_Image()
            : Qul::Private::Items::ItemBase ::ExtraStorage_itemExtraProperties<Qul::Private::Items::Image  >(this)
        {}
    } truckgreen;
    struct truckred_Image : Qul::Private::Items::Image , public Qul::Private::Items::ItemBase ::ExtraStorage_itemExtraProperties<Qul::Private::Items::Image  > {
        truckred_Image()
            : Qul::Private::Items::ItemBase ::ExtraStorage_itemExtraProperties<Qul::Private::Items::Image  >(this)
        {}
    } truckred;
    struct hillhold_Image : Qul::Private::Items::Image , public Qul::Private::Items::ItemBase ::ExtraStorage_itemExtraProperties<Qul::Private::Items::Image  > {
        hillhold_Image()
            : Qul::Private::Items::ItemBase ::ExtraStorage_itemExtraProperties<Qul::Private::Items::Image  >(this)
        {}
    } hillhold;
    struct consoletop_Image : Qul::Private::Items::Image , public Qul::Private::Items::ItemBase ::ExtraStorage_itemExtraProperties<Qul::Private::Items::Image  > {
        consoletop_Image()
            : Qul::Private::Items::ItemBase ::ExtraStorage_itemExtraProperties<Qul::Private::Items::Image  >(this)
        {}
    } consoletop;
    struct consolebottom_Image : Qul::Private::Items::Image , public Qul::Private::Items::ItemBase ::ExtraStorage_itemExtraProperties<Qul::Private::Items::Image  > {
        consolebottom_Image()
            : Qul::Private::Items::ItemBase ::ExtraStorage_itemExtraProperties<Qul::Private::Items::Image  >(this)
        {}
    } consolebottom;
    struct drive_Image : Qul::Private::Items::Image , public Qul::Private::Items::ItemBase ::ExtraStorage_itemExtraProperties<Qul::Private::Items::Image  > {
        drive_Image()
            : Qul::Private::Items::ItemBase ::ExtraStorage_itemExtraProperties<Qul::Private::Items::Image  >(this)
        {}
    } drive;
    struct reverse_Image : Qul::Private::Items::Image , public Qul::Private::Items::ItemBase ::ExtraStorage_itemExtraProperties<Qul::Private::Items::Image  > {
        reverse_Image()
            : Qul::Private::Items::ItemBase ::ExtraStorage_itemExtraProperties<Qul::Private::Items::Image  >(this)
        {}
    } reverse;
    struct neutral_Image : Qul::Private::Items::Image , public Qul::Private::Items::ItemBase ::ExtraStorage_itemExtraProperties<Qul::Private::Items::Image  > {
        neutral_Image()
            : Qul::Private::Items::ItemBase ::ExtraStorage_itemExtraProperties<Qul::Private::Items::Image  >(this)
        {}
    } neutral;
    struct sport_Image : Qul::Private::Items::Image , public Qul::Private::Items::ItemBase ::ExtraStorage_itemExtraProperties<Qul::Private::Items::Image  > {
        sport_Image()
            : Qul::Private::Items::ItemBase ::ExtraStorage_itemExtraProperties<Qul::Private::Items::Image  >(this)
        {}
    } sport;
    struct hbeam_Image : Qul::Private::Items::Image , public Qul::Private::Items::ItemBase ::ExtraStorage_itemExtraProperties<Qul::Private::Items::Image  > {
        hbeam_Image()
            : Qul::Private::Items::ItemBase ::ExtraStorage_itemExtraProperties<Qul::Private::Items::Image  >(this)
        {}
    } hbeam;
    struct lbeam_Image : Qul::Private::Items::Image , public Qul::Private::Items::ItemBase ::ExtraStorage_itemExtraProperties<Qul::Private::Items::Image  > {
        lbeam_Image()
            : Qul::Private::Items::ItemBase ::ExtraStorage_itemExtraProperties<Qul::Private::Items::Image  >(this)
        {}
    } lbeam;
    struct breakfault_Image : Qul::Private::Items::Image , public Qul::Private::Items::ItemBase ::ExtraStorage_itemExtraProperties<Qul::Private::Items::Image  > {
        breakfault_Image()
            : Qul::Private::Items::ItemBase ::ExtraStorage_itemExtraProperties<Qul::Private::Items::Image  >(this)
        {}
    } breakfault;
    struct seatbelt_Image : Qul::Private::Items::Image , public Qul::Private::Items::ItemBase ::ExtraStorage_itemExtraProperties<Qul::Private::Items::Image  > {
        seatbelt_Image()
            : Qul::Private::Items::ItemBase ::ExtraStorage_itemExtraProperties<Qul::Private::Items::Image  >(this)
        {}
    } seatbelt;
    struct airbag_Image : Qul::Private::Items::Image , public Qul::Private::Items::ItemBase ::ExtraStorage_itemExtraProperties<Qul::Private::Items::Image  > {
        airbag_Image()
            : Qul::Private::Items::ItemBase ::ExtraStorage_itemExtraProperties<Qul::Private::Items::Image  >(this)
        {}
    } airbag;
    struct lowcoolant_Image : Qul::Private::Items::Image , public Qul::Private::Items::ItemBase ::ExtraStorage_itemExtraProperties<Qul::Private::Items::Image  > {
        lowcoolant_Image()
            : Qul::Private::Items::ItemBase ::ExtraStorage_itemExtraProperties<Qul::Private::Items::Image  >(this)
        {}
    } lowcoolant;
    struct indfrontfog_Image : Qul::Private::Items::Image , public Qul::Private::Items::ItemBase ::ExtraStorage_itemExtraProperties<Qul::Private::Items::Image  > {
        indfrontfog_Image()
            : Qul::Private::Items::ItemBase ::ExtraStorage_itemExtraProperties<Qul::Private::Items::Image  >(this)
        {}
    } indfrontfog;
    struct positionlights_Image : Qul::Private::Items::Image , public Qul::Private::Items::ItemBase ::ExtraStorage_itemExtraProperties<Qul::Private::Items::Image  > {
        positionlights_Image()
            : Qul::Private::Items::ItemBase ::ExtraStorage_itemExtraProperties<Qul::Private::Items::Image  >(this)
        {}
    } positionlights;
    struct limphome_Image : Qul::Private::Items::Image , public Qul::Private::Items::ItemBase ::ExtraStorage_itemExtraProperties<Qul::Private::Items::Image  > {
        limphome_Image()
            : Qul::Private::Items::ItemBase ::ExtraStorage_itemExtraProperties<Qul::Private::Items::Image  >(this)
        {}
    } limphome;
    struct indsteering_Image : Qul::Private::Items::Image , public Qul::Private::Items::ItemBase ::ExtraStorage_itemExtraProperties<Qul::Private::Items::Image  > {
        indsteering_Image()
            : Qul::Private::Items::ItemBase ::ExtraStorage_itemExtraProperties<Qul::Private::Items::Image  >(this)
        {}
    } indsteering;
    struct dooropen_Image : Qul::Private::Items::Image , public Qul::Private::Items::ItemBase ::ExtraStorage_itemExtraProperties<Qul::Private::Items::Image  > {
        dooropen_Image()
            : Qul::Private::Items::ItemBase ::ExtraStorage_itemExtraProperties<Qul::Private::Items::Image  >(this)
        {}
    } dooropen;
    struct hvbattery_Image : Qul::Private::Items::Image , public Qul::Private::Items::ItemBase ::ExtraStorage_itemExtraProperties<Qul::Private::Items::Image  > {
        hvbattery_Image()
            : Qul::Private::Items::ItemBase ::ExtraStorage_itemExtraProperties<Qul::Private::Items::Image  >(this)
        {}
    } hvbattery;
    struct serviceDisconnect_Image : Qul::Private::Items::Image , public Qul::Private::Items::ItemBase ::ExtraStorage_itemExtraProperties<Qul::Private::Items::Image  > {
        serviceDisconnect_Image()
            : Qul::Private::Items::ItemBase ::ExtraStorage_itemExtraProperties<Qul::Private::Items::Image  >(this)
        {}
    } serviceDisconnect;
    struct coolanttemp_Image : Qul::Private::Items::Image , public Qul::Private::Items::ItemBase ::ExtraStorage_itemExtraProperties<Qul::Private::Items::Image  > {
        coolanttemp_Image()
            : Qul::Private::Items::ItemBase ::ExtraStorage_itemExtraProperties<Qul::Private::Items::Image  >(this)
        {}
    } coolanttemp;
    struct indright_Image : Qul::Private::Items::Image , public Qul::Private::Items::ItemBase ::ExtraStorage_itemExtraProperties<Qul::Private::Items::Image  > {
        indright_Image()
            : Qul::Private::Items::ItemBase ::ExtraStorage_itemExtraProperties<Qul::Private::Items::Image  >(this)
        {}
    } indright;
    struct indleft_Image : Qul::Private::Items::Image , public Qul::Private::Items::ItemBase ::ExtraStorage_itemExtraProperties<Qul::Private::Items::Image  > {
        indleft_Image()
            : Qul::Private::Items::ItemBase ::ExtraStorage_itemExtraProperties<Qul::Private::Items::Image  >(this)
        {}
    } indleft;
    struct speedText_Text : Qul::Private::Items::TextLight  {
    } speedText;
    struct kmph_StaticText : Qul::Private::Items::StaticText  {
    } kmph;
    struct statictext_StaticText : Qul::Private::Items::StaticText  {
    } statictext;
    struct odoval_Text : Qul::Private::Items::TextLight  {
    } odoval;
    struct statictext_2_StaticText : Qul::Private::Items::StaticText  {
    } statictext_2;
    struct row_Row : Qul::Private::Items::Row  {
    } row;
    struct rectangle_Rectangle : Qul::Private::Items::Rectangle  {
    } rectangle;
    struct statictext_3_StaticText : Qul::Private::Items::StaticText  {
    } statictext_3;
    struct tripval_Text : Qul::Private::Items::TextLight  {
    } tripval;
    struct statictext_4_StaticText : Qul::Private::Items::StaticText  {
    } statictext_4;
    struct row_2_Row : Qul::Private::Items::Row  {
    } row_2;
    struct rectangle_2_Rectangle : Qul::Private::Items::Rectangle  {
    } rectangle_2;
    struct iconmaxspeed_Image : Qul::Private::Items::Image , public Qul::Private::Items::ItemBase ::ExtraStorage_itemExtraProperties<Qul::Private::Items::Image  > {
        iconmaxspeed_Image()
            : Qul::Private::Items::ItemBase ::ExtraStorage_itemExtraProperties<Qul::Private::Items::Image  >(this)
        {}
    } iconmaxspeed;
    struct iconlowsoc_Image : Qul::Private::Items::Image , public Qul::Private::Items::ItemBase ::ExtraStorage_itemExtraProperties<Qul::Private::Items::Image  > {
        iconlowsoc_Image()
            : Qul::Private::Items::ItemBase ::ExtraStorage_itemExtraProperties<Qul::Private::Items::Image  >(this)
        {}
    } iconlowsoc;
    struct iconregen_Image : Qul::Private::Items::Image , public Qul::Private::Items::ItemBase ::ExtraStorage_itemExtraProperties<Qul::Private::Items::Image  > {
        iconregen_Image()
            : Qul::Private::Items::ItemBase ::ExtraStorage_itemExtraProperties<Qul::Private::Items::Image  >(this)
        {}
    } iconregen;
    struct bgbattery_Image : Qul::Private::Items::Image , public Qul::Private::Items::ItemBase ::ExtraStorage_itemExtraProperties<Qul::Private::Items::Image  > {
        bgbattery_Image()
            : Qul::Private::Items::ItemBase ::ExtraStorage_itemExtraProperties<Qul::Private::Items::Image  >(this)
        {}
    } bgbattery;
    struct rectangle_3_Rectangle : Qul::Private::Items::Rectangle  {
    } rectangle_3;
    struct rectangle_4_Rectangle : Qul::Private::Items::Rectangle  {
    } rectangle_4;
    struct batterybar_Rectangle : Qul::Private::Items::Rectangle  {
    } batterybar;
    struct rectangle_5_Rectangle : Qul::Private::Items::Rectangle  {
    } rectangle_5;
    struct batper_Text : Qul::Private::Items::TextLight  {
    } batper;
    struct statictext_5_StaticText : Qul::Private::Items::StaticText  {
    } statictext_5;
    struct row_3_Row : Qul::Private::Items::Row  {
    } row_3;
    struct rectangle_6_Rectangle : Qul::Private::Items::Rectangle  {
    } rectangle_6;
    struct bgrange_Image : Qul::Private::Items::Image , public Qul::Private::Items::ItemBase ::ExtraStorage_itemExtraProperties<Qul::Private::Items::Image  > {
        bgrange_Image()
            : Qul::Private::Items::ItemBase ::ExtraStorage_itemExtraProperties<Qul::Private::Items::Image  >(this)
        {}
    } bgrange;
    struct rangename_StaticText : Qul::Private::Items::StaticText  {
    } rangename;
    struct rangeval_Text : Qul::Private::Items::TextLight  {
    } rangeval;
    struct statictext_6_StaticText : Qul::Private::Items::StaticText  {
    } statictext_6;
    struct row_4_Row : Qul::Private::Items::Row  {
    } row_4;
    struct rectangle_7_Rectangle : Qul::Private::Items::Rectangle  {
    } rectangle_7;
    struct homescreen_Rectangle : Qul::Private::Items::Rectangle  {
    } homescreen;
    struct bgcharge_Image : Qul::Private::Items::Image , public Qul::Private::Items::ItemBase ::ExtraStorage_itemExtraProperties<Qul::Private::Items::Image  > {
        bgcharge_Image()
            : Qul::Private::Items::ItemBase ::ExtraStorage_itemExtraProperties<Qul::Private::Items::Image  >(this)
        {}
    } bgcharge;
    struct rectangle_8_Rectangle : Qul::Private::Items::Rectangle  {
    } rectangle_8;
    struct rectangle_9_Rectangle : Qul::Private::Items::Rectangle  {
    } rectangle_9;
    struct chargebatterybar_Rectangle : Qul::Private::Items::Rectangle  {
    } chargebatterybar;
    struct rectangle_10_Rectangle : Qul::Private::Items::Rectangle  {
    } rectangle_10;
    struct chargebatper_Text : Qul::Private::Items::TextLight  {
    } chargebatper;
    struct statictext_7_StaticText : Qul::Private::Items::StaticText  {
    } statictext_7;
    struct row_5_Row : Qul::Private::Items::Row  {
    } row_5;
    struct rectangle_11_Rectangle : Qul::Private::Items::Rectangle  {
    } rectangle_11;
    struct idchargeicon_Image : Qul::Private::Items::Image , public Qul::Private::Items::ItemBase ::ExtraStorage_itemExtraProperties<Qul::Private::Items::Image  > {
        idchargeicon_Image()
            : Qul::Private::Items::ItemBase ::ExtraStorage_itemExtraProperties<Qul::Private::Items::Image  >(this)
        {}
    } idchargeicon;
    struct idchargecomp_Image : Qul::Private::Items::Image , public Qul::Private::Items::ItemBase ::ExtraStorage_itemExtraProperties<Qul::Private::Items::Image  > {
        idchargecomp_Image()
            : Qul::Private::Items::ItemBase ::ExtraStorage_itemExtraProperties<Qul::Private::Items::Image  >(this)
        {}
    } idchargecomp;
    struct chargingfailed_Image : Qul::Private::Items::Image , public Qul::Private::Items::ItemBase ::ExtraStorage_itemExtraProperties<Qul::Private::Items::Image  > {
        chargingfailed_Image()
            : Qul::Private::Items::ItemBase ::ExtraStorage_itemExtraProperties<Qul::Private::Items::Image  >(this)
        {}
    } chargingfailed;
    struct idchargingtext_Text : Qul::Private::Items::TextLight  {
    } idchargingtext;
    struct csrangeyval_Text : Qul::Private::Items::TextLight  {
    } csrangeyval;
    struct chargetimename_StaticText : Qul::Private::Items::StaticText  {
    } chargetimename;
    struct chargehrs_Text : Qul::Private::Items::TextLight  {
    } chargehrs;
    struct hrsunit_StaticText : Qul::Private::Items::StaticText  {
    } hrsunit;
    struct chargemins_Text : Qul::Private::Items::TextLight  {
    } chargemins;
    struct minsunit_StaticText : Qul::Private::Items::StaticText  {
    } minsunit;
    struct row_6_Row : Qul::Private::Items::Row  {
    } row_6;
    struct rectangle_12_Rectangle : Qul::Private::Items::Rectangle  {
    } rectangle_12;
    struct energyname_StaticText : Qul::Private::Items::StaticText  {
    } energyname;
    struct energyval_Text : Qul::Private::Items::TextLight  {
    } energyval;
    struct energyunit_StaticText : Qul::Private::Items::StaticText  {
    } energyunit;
    struct row_7_Row : Qul::Private::Items::Row  {
    } row_7;
    struct rectangle_13_Rectangle : Qul::Private::Items::Rectangle  {
    } rectangle_13;
    struct batterytempname_StaticText : Qul::Private::Items::StaticText  {
    } batterytempname;
    struct battempval_Text : Qul::Private::Items::TextLight  {
    } battempval;
    struct idtempunit_Image : Qul::Private::Items::Image , public Qul::Private::Items::ItemBase ::ExtraStorage_itemExtraProperties<Qul::Private::Items::Image  > {
        idtempunit_Image()
            : Qul::Private::Items::ItemBase ::ExtraStorage_itemExtraProperties<Qul::Private::Items::Image  >(this)
        {}
    } idtempunit;
    struct row_8_Row : Qul::Private::Items::Row  {
    } row_8;
    struct rectangle_14_Rectangle : Qul::Private::Items::Rectangle  {
    } rectangle_14;
    struct chargescreen_Rectangle : Qul::Private::Items::Rectangle , public Qul::Private::Items::ItemBase ::ExtraStorage_itemExtraProperties<Qul::Private::Items::Rectangle  > {
        chargescreen_Rectangle()
            : Qul::Private::Items::ItemBase ::ExtraStorage_itemExtraProperties<Qul::Private::Items::Rectangle  >(this)
        {}
    } chargescreen;
    struct warningmsg_Text : Qul::Private::Items::TextLight  {
    } warningmsg;
    struct bgdate_Image : Qul::Private::Items::Image , public Qul::Private::Items::ItemBase ::ExtraStorage_itemExtraProperties<Qul::Private::Items::Image  > {
        bgdate_Image()
            : Qul::Private::Items::ItemBase ::ExtraStorage_itemExtraProperties<Qul::Private::Items::Image  >(this)
        {}
    } bgdate;
    struct tday_Text : Qul::Private::Items::TextLight  {
    } tday;
    struct statictext_8_StaticText : Qul::Private::Items::StaticText  {
    } statictext_8;
    struct tmon_Text : Qul::Private::Items::TextLight  {
    } tmon;
    struct statictext_9_StaticText : Qul::Private::Items::StaticText  {
    } statictext_9;
    struct tyear_Text : Qul::Private::Items::TextLight  {
    } tyear;
    struct row_9_Row : Qul::Private::Items::Row  {
    } row_9;
    struct daterect_Rectangle : Qul::Private::Items::Rectangle  {
    } daterect;
    struct bgtime_Image : Qul::Private::Items::Image , public Qul::Private::Items::ItemBase ::ExtraStorage_itemExtraProperties<Qul::Private::Items::Image  > {
        bgtime_Image()
            : Qul::Private::Items::ItemBase ::ExtraStorage_itemExtraProperties<Qul::Private::Items::Image  >(this)
        {}
    } bgtime;
    struct thour_Text : Qul::Private::Items::TextLight  {
    } thour;
    struct statictext_10_StaticText : Qul::Private::Items::StaticText  {
    } statictext_10;
    struct tmin_Text : Qul::Private::Items::TextLight  {
    } tmin;
    struct tampm_Text : Qul::Private::Items::TextLight  {
    } tampm;
    struct row_10_Row : Qul::Private::Items::Row  {
    } row_10;
    struct timerect_Rectangle : Qul::Private::Items::Rectangle  {
    } timerect;
    struct parking_Image : Qul::Private::Items::Image , public Qul::Private::Items::ItemBase ::ExtraStorage_itemExtraProperties<Qul::Private::Items::Image  > {
        parking_Image()
            : Qul::Private::Items::ItemBase ::ExtraStorage_itemExtraProperties<Qul::Private::Items::Image  >(this)
        {}
    } parking;
    struct hvbatteryfault_Image : Qul::Private::Items::Image , public Qul::Private::Items::ItemBase ::ExtraStorage_itemExtraProperties<Qul::Private::Items::Image  > {
        hvbatteryfault_Image()
            : Qul::Private::Items::ItemBase ::ExtraStorage_itemExtraProperties<Qul::Private::Items::Image  >(this)
        {}
    } hvbatteryfault;
    struct lvbatttery_Image : Qul::Private::Items::Image , public Qul::Private::Items::ItemBase ::ExtraStorage_itemExtraProperties<Qul::Private::Items::Image  > {
        lvbatttery_Image()
            : Qul::Private::Items::ItemBase ::ExtraStorage_itemExtraProperties<Qul::Private::Items::Image  >(this)
        {}
    } lvbatttery;
    struct bmsfault_Image : Qul::Private::Items::Image , public Qul::Private::Items::ItemBase ::ExtraStorage_itemExtraProperties<Qul::Private::Items::Image  > {
        bmsfault_Image()
            : Qul::Private::Items::ItemBase ::ExtraStorage_itemExtraProperties<Qul::Private::Items::Image  >(this)
        {}
    } bmsfault;
    struct thernalrunaway_Image : Qul::Private::Items::Image , public Qul::Private::Items::ItemBase ::ExtraStorage_itemExtraProperties<Qul::Private::Items::Image  > {
        thernalrunaway_Image()
            : Qul::Private::Items::ItemBase ::ExtraStorage_itemExtraProperties<Qul::Private::Items::Image  >(this)
        {}
    } thernalrunaway;
    struct batlowcoolant_Image : Qul::Private::Items::Image , public Qul::Private::Items::ItemBase ::ExtraStorage_itemExtraProperties<Qul::Private::Items::Image  > {
        batlowcoolant_Image()
            : Qul::Private::Items::ItemBase ::ExtraStorage_itemExtraProperties<Qul::Private::Items::Image  >(this)
        {}
    } batlowcoolant;
    struct commontt_Rectangle : Qul::Private::Items::Rectangle  {
    } commontt;
    struct devicdetails_StaticText : Qul::Private::Items::StaticText  {
    } devicdetails;
    struct swver_StaticText : Qul::Private::Items::StaticText  {
    } swver;
    struct swver1_StaticText : Qul::Private::Items::StaticText  {
    } swver1;
    struct seversion_Text : Qul::Private::Items::TextLight  {
    } seversion;
    struct iswver_Row : Qul::Private::Items::Row  {
    } iswver;
    struct rectangle_16_Rectangle : Qul::Private::Items::Rectangle  {
    } rectangle_16;
    struct hwver_StaticText : Qul::Private::Items::StaticText  {
    } hwver;
    struct hwver1_StaticText : Qul::Private::Items::StaticText  {
    } hwver1;
    struct hwversion_Text : Qul::Private::Items::TextLight  {
    } hwversion;
    struct ihwver_Row : Qul::Private::Items::Row  {
    } ihwver;
    struct rectangle_17_Rectangle : Qul::Private::Items::Rectangle  {
    } rectangle_17;
    struct slnum_StaticText : Qul::Private::Items::StaticText  {
    } slnum;
    struct slnum1_StaticText : Qul::Private::Items::StaticText  {
    } slnum1;
    struct slnumtxt_Text : Qul::Private::Items::TextLight  {
    } slnumtxt;
    struct iserialnum_Row : Qul::Private::Items::Row  {
    } iserialnum;
    struct rectangle_18_Rectangle : Qul::Private::Items::Rectangle  {
    } rectangle_18;
    struct column_Column : Qul::Private::Items::Column  {
    } column;
    struct rectangle_15_Rectangle : Qul::Private::Items::Rectangle  {
    } rectangle_15;
    struct deviceinfo_Rectangle : Qul::Private::Items::Rectangle  {
    } deviceinfo;
    struct main_Rectangle : Qul::Private::Items::Rectangle , public Qul::Private::Items::ItemBase ::ExtraStorage_itemExtraProperties<Qul::Private::Items::Rectangle  > {
        main_Rectangle()
            : Qul::Private::Items::ItemBase ::ExtraStorage_itemExtraProperties<Qul::Private::Items::Rectangle  >(this)
        {}
        void updateSpeedInfo(int mspeed, int modo, int mtrip);
        int getBitPosition(int iVal);
    } main;
    Qul::Property<int> speed;
    Qul::Property<int> iCurspeed;
    Qul::Property<int> iSocval;
    Qul::Property<int> iDriveMode;
    Qul::Property<int> itimeval;
    Qul::Property<int> isoctimeval;
    Qul::Property<int> irange;
    Qul::Property<int> iodo;
    Qul::Property<int> itrip;
    Qul::Property<int> icursoc;
    Qul::Property<int> icurenergyavg;
    Qul::Property<int> icurenergycon;
    Qul::Property<int> isedit;
    Qul::Property<int> istate;
    Qul::Property<int> icurchargestatus;
    Qul::Property<int> icursteering;
    Qul::Property<int> ibattemp;
    Qul::Property<int> icurday;
    Qul::Property<int> icurmon;
    Qul::Property<int> icuryear;
    Qul::Property<int> icurhour;
    Qul::Property<int> icurmin;
    Qul::Property<int> iodokm;
    Qul::Property<int> itripkm;
    Qul::Property<int> ichargetime;
    Qul::Property<int> ichargemin;
    Qul::Property<int> ichargehrs;
    Qul::Property<bool> bcursteering;
    Qul::Property<bool> btripreset;
    Qul::Property<bool> bignition;
    Qul::Property<bool> bcurpm;
    Qul::Property<bool> bLowsoc;
    Qul::Property<bool> bHillhold;
    Qul::Property<bool> bchargemode;
    Qul::Property<bool> bHighbeam;
    Qul::Property<bool> bLowbeam;
    Qul::Property<bool> bParking;
    Qul::Property<bool> bBreakfault;
    Qul::Property<bool> bSeatbelt;
    Qul::Property<bool> bAirbag;
    Qul::Property<bool> bLvbatttery;
    Qul::Property<bool> bBmsfault;
    Qul::Property<bool> bThernalrunaway;
    Qul::Property<bool> bLowcoolant;
    Qul::Property<bool> bbatlowcoolant;
    Qul::Property<bool> bCoolanttemp;
    Qul::Property<bool> bFrontfog;
    Qul::Property<bool> bPositionlights;
    Qul::Property<bool> bDooropen;
    Qul::Property<bool> bHvbattery;
    Qul::Property<bool> bIndright;
    Qul::Property<bool> bIndleft;
    Qul::Property<bool> bMaxspeed;
    Qul::Property<bool> bRegen;
    Qul::Property<bool> bwarning;
    Qul::Property<bool> btruckgreen;
    Qul::Property<bool> btruckred;
    Qul::Property<bool> bdriveenable;
    Qul::Property<bool> bdrivedisable;
    Qul::Property<bool> bServiceDisconnect;
    Qul::Property<bool> bHvbatteryfault;
    Qul::Property<bool> bLimpHome;
    Qul::Property<bool> isdarktheme;
    Qul::Property<bool> bdeviceinfo;
    Qul::Property<bool> bSplashScreen;
    Qul::Property<Qul::Private::String> smessage;
    Qul::Property<Qul::Private::String> rengavgval;
    Qul::Property<Qul::Private::String> rengconval;
    Qul::Property<Qul::Private::String> rswvermsg;
    Qul::Property<Qul::Private::String> rhwvermsg;
    Qul::Property<Qul::Private::String> scolor_dark;
    Qul::Property<Qul::Private::String> scolor;
    Qul::Property<Qul::Private::String> scolor_light;
    Qul::Property<Qul::Private::String> svinnummsg;
    Qul::Property<Qul::Private::String> sslnummsg;
    Qul::Property<Qul::Private::String> shwvermsg;
    Qul::Property<Qul::Private::String> sswvermsg;
    Qul::Property<Qul::Private::String> stxtmessage0;
    Qul::Property<Qul::Private::String> stxtmessage1;
    Qul::Property<Qul::Private::String> stxtmessage2;
    Qul::Property<Qul::Private::String> stxtmessage3;
    Qul::Property<Qul::Private::String> stxtmessage4;
    Qul::Property<Qul::Private::String> stxtmessage5;
    Qul::Property<Qul::Private::String> stxtmessage6;
    Qul::Property<Qul::Private::String> stxtmessage7;
    Qul::Property<Qul::Private::String> stxtmessage8;
    Qul::Property<Qul::Private::String> stxtmessage9;
    Qul::Property<Qul::Private::String> stxtmessage10;
    Qul::Property<Qul::Private::String> stxtmessage11;
    Qul::Property<Qul::Private::String> stxtmessage12;
    Qul::Property<Qul::Private::String> stxtmessage14;
    Qul::Property<Qul::Private::String> stxtmessage15;
    Qul::Property<Qul::Private::String> stxtmessage16;
    Qul::Property<Qul::Private::String> stxtmessage17;
    Qul::Property<Qul::Private::String> stxtmessage18;
    Qul::Property<Qul::Private::String> stxtmessage19;
    Qul::Property<Qul::Private::String> stxtmessage20;
    Qul::Property<Qul::Private::String> stxtmessage21;
    Qul::Property<Qul::Private::String> stxtmessage22;
    Qul::Property<Qul::Private::String> stxtmessage23;
    Qul::Property<Qul::Private::String> stxtmesCanError;
    Qul::Property<Qul::Private::String> stxtmesNoCanData;
    Qul::Property<Qul::Private::String> stxtmesRtcSetError;
    Qul::Property<Qul::Private::String> stxtmesRtcError;
    Qul::Property<Qul::Private::String> stxtmestripResetSuccess;
    Qul::Property<Qul::Private::String> stxtmesbuttonError;
    Qul::Property<Qul::SharedImage> bg_chargescreen;
    Qul::Property<Qul::SharedImage> logo_dark;
    Qul::Property<Qul::SharedImage> logo_splashscreen;
    Qul::Property<Qul::SharedImage> icon_airbag;
    Qul::Property<Qul::SharedImage> console_top;
    Qul::Property<Qul::SharedImage> icon_lvbatttery;
    Qul::Property<Qul::SharedImage> icon_foglight;
    Qul::Property<Qul::SharedImage> icon_lowbeam;
    Qul::Property<Qul::SharedImage> icon_highbeam;
    Qul::Property<Qul::SharedImage> icon_dooropen;
    Qul::Property<Qul::SharedImage> icon_maxspeed;
    Qul::Property<Qul::SharedImage> console_bottom;
    Qul::Property<Qul::SharedImage> icon_limphome;
    Qul::Property<Qul::SharedImage> icon_bmsfault;
    Qul::Property<Qul::SharedImage> icon_coolanttemp;
    Qul::Property<Qul::SharedImage> icon_positionlights;
    Qul::Property<Qul::SharedImage> icon_thernalrunaway;
    Qul::Property<Qul::SharedImage> icon_lowcoolant;
    Qul::Property<Qul::SharedImage> icon_batlowcoolant;
    Qul::Property<Qul::SharedImage> icon_seatbelt;
    Qul::Property<Qul::SharedImage> icon_charging;
    Qul::Property<Qul::SharedImage> icon_hvbattery;
    Qul::Property<Qul::SharedImage> icon_parking;
    Qul::Property<Qul::SharedImage> icon_breakfault;
    Qul::Property<Qul::SharedImage> icon_indicatorleft;
    Qul::Property<Qul::SharedImage> icon_indicatorright;
    Qul::Property<Qul::SharedImage> icon_chargefailed;
    Qul::Property<Qul::SharedImage> icon_steeringfailure;
    Qul::Property<Qul::SharedImage> icon_steeringworking;
    Qul::Property<Qul::SharedImage> icon_chargecomplete;
    Qul::Property<Qul::SharedImage> icon_hvbatteryfault;
    Qul::Property<Qul::SharedImage> bg_date;
    Qul::Property<Qul::SharedImage> bg_time;
    Qul::Property<Qul::SharedImage> bg_range;
    Qul::Property<Qul::SharedImage> bg_battery;
    Qul::Property<Qul::SharedImage> icon_drive;
    Qul::Property<Qul::SharedImage> icon_sport;
    Qul::Property<Qul::SharedImage> icon_regen;
    Qul::Property<Qul::SharedImage> icon_neutral;
    Qul::Property<Qul::SharedImage> icon_reverse;
    Qul::Property<Qul::SharedImage> icon_emptysoc;
    Qul::Property<Qul::SharedImage> icon_hillhold;
    Qul::Property<Qul::SharedImage> icon_truck_red;
    Qul::Property<Qul::SharedImage> icon_truck_green;
    Qul::Property<Qul::SharedImage> icon_servicedisconnect;
    Qul::Property<Qul::SharedImage> icon_tempunit;
    Qul::Private::Items::ComponentAttachedType  ComponentAttachedType_node;
    struct ComponentAttachedType_node_onCompleted_bindingFunctor {
        hmimain *self;
        ComponentAttachedType_node_onCompleted_bindingFunctor(hmimain *self_) : self(self_) {}
        void operator()() const;
    };
    static void ComponentAttachedType_node_onCompleted_binding_slot(hmimain *self) { return ComponentAttachedType_node_onCompleted_bindingFunctor(self)(); }
    Qul::Private::Slot<hmimain, void()> ComponentAttachedType_node_onCompleted_binding;
    struct timer_onTriggered_bindingFunctor {
        hmimain *self;
        timer_onTriggered_bindingFunctor(hmimain *self_) : self(self_) {}
        void operator()() const;
    };
    static void timer_onTriggered_binding_slot(hmimain *self) { return timer_onTriggered_bindingFunctor(self)(); }
    Qul::Private::Slot<hmimain, void()> timer_onTriggered_binding;
    struct triptimer_onTriggered_bindingFunctor {
        hmimain *self;
        triptimer_onTriggered_bindingFunctor(hmimain *self_) : self(self_) {}
        void operator()() const;
    };
    static void triptimer_onTriggered_binding_slot(hmimain *self) { return triptimer_onTriggered_bindingFunctor(self)(); }
    Qul::Private::Slot<hmimain, void()> triptimer_onTriggered_binding;
    struct deviceinfotimer_onTriggered_bindingFunctor {
        hmimain *self;
        deviceinfotimer_onTriggered_bindingFunctor(hmimain *self_) : self(self_) {}
        void operator()() const;
    };
    static void deviceinfotimer_onTriggered_binding_slot(hmimain *self) { return deviceinfotimer_onTriggered_bindingFunctor(self)(); }
    Qul::Private::Slot<hmimain, void()> deviceinfotimer_onTriggered_binding;
    struct main__onDateTimeChanged_bindingFunctor {
        hmimain *self;
        main__onDateTimeChanged_bindingFunctor(hmimain *self_) : self(self_) {}
        void operator()(int mday, int mmonth, int myear, int mhour, int mminute, bool mPM, int medit, int mstate) const;
    };
    static void main__onDateTimeChanged_binding_slot(hmimain *self, int mday, int mmonth, int myear, int mhour, int mminute, bool mPM, int medit, int mstate) { return main__onDateTimeChanged_bindingFunctor(self)(mday, mmonth, myear, mhour, mminute, mPM, medit, mstate); }
    Qul::Private::Slot<hmimain, void(int, int, int, int, int, bool, int, int)> main__onDateTimeChanged_binding;
    struct main__onDeviceInfoChanged_bindingFunctor {
        hmimain *self;
        main__onDeviceInfoChanged_bindingFunctor(hmimain *self_) : self(self_) {}
        void operator()(int mswversion, int mhwversion, int mslnum) const;
    };
    static void main__onDeviceInfoChanged_binding_slot(hmimain *self, int mswversion, int mhwversion, int mslnum) { return main__onDeviceInfoChanged_bindingFunctor(self)(mswversion, mhwversion, mslnum); }
    Qul::Private::Slot<hmimain, void(int, int, int)> main__onDeviceInfoChanged_binding;
    struct main__onHwStatusChanged_bindingFunctor {
        hmimain *self;
        main__onHwStatusChanged_bindingFunctor(hmimain *self_) : self(self_) {}
        void operator()(bool mignition, bool mleftind, bool mrightind, bool mhighbeam, bool mlowbeam, bool mdoorind, bool mposition, bool mseatybelt, bool mfoglight) const;
    };
    static void main__onHwStatusChanged_binding_slot(hmimain *self, bool mignition, bool mleftind, bool mrightind, bool mhighbeam, bool mlowbeam, bool mdoorind, bool mposition, bool mseatybelt, bool mfoglight) { return main__onHwStatusChanged_bindingFunctor(self)(mignition, mleftind, mrightind, mhighbeam, mlowbeam, mdoorind, mposition, mseatybelt, mfoglight); }
    Qul::Private::Slot<hmimain, void(bool, bool, bool, bool, bool, bool, bool, bool, bool)> main__onHwStatusChanged_binding;
    struct main__onStatus3InfoChanged_bindingFunctor {
        hmimain *self;
        main__onStatus3InfoChanged_bindingFunctor(hmimain *self_) : self(self_) {}
        void operator()(bool mreadytodrive, bool mdrivedisabled, bool mserdisc, bool mhvbatfault, bool mlowsoc, bool mbatlowcooltemp, bool mlimphome, bool mhillhold) const;
    };
    static void main__onStatus3InfoChanged_binding_slot(hmimain *self, bool mreadytodrive, bool mdrivedisabled, bool mserdisc, bool mhvbatfault, bool mlowsoc, bool mbatlowcooltemp, bool mlimphome, bool mhillhold) { return main__onStatus3InfoChanged_bindingFunctor(self)(mreadytodrive, mdrivedisabled, mserdisc, mhvbatfault, mlowsoc, mbatlowcooltemp, mlimphome, mhillhold); }
    Qul::Private::Slot<hmimain, void(bool, bool, bool, bool, bool, bool, bool, bool)> main__onStatus3InfoChanged_binding;
    struct main__onStatus2InfoChanged_bindingFunctor {
        hmimain *self;
        main__onStatus2InfoChanged_bindingFunctor(hmimain *self_) : self(self_) {}
        void operator()(bool mlowcoolant, bool mbreakfault, bool mparking, bool mairbag) const;
    };
    static void main__onStatus2InfoChanged_binding_slot(hmimain *self, bool mlowcoolant, bool mbreakfault, bool mparking, bool mairbag) { return main__onStatus2InfoChanged_bindingFunctor(self)(mlowcoolant, mbreakfault, mparking, mairbag); }
    Qul::Private::Slot<hmimain, void(bool, bool, bool, bool)> main__onStatus2InfoChanged_binding;
    struct main__onStatus1InfoChanged_bindingFunctor {
        hmimain *self;
        main__onStatus1InfoChanged_bindingFunctor(hmimain *self_) : self(self_) {}
        void operator()(bool mregen, bool mmaxspeed, bool mlvbatttery, int mcharge, int msteering) const;
    };
    static void main__onStatus1InfoChanged_binding_slot(hmimain *self, bool mregen, bool mmaxspeed, bool mlvbatttery, int mcharge, int msteering) { return main__onStatus1InfoChanged_bindingFunctor(self)(mregen, mmaxspeed, mlvbatttery, mcharge, msteering); }
    Qul::Private::Slot<hmimain, void(bool, bool, bool, int, int)> main__onStatus1InfoChanged_binding;
    struct main__onStatus0InfoChanged_bindingFunctor {
        hmimain *self;
        main__onStatus0InfoChanged_bindingFunctor(hmimain *self_) : self(self_) {}
        void operator()(bool mhvbattery, bool mcoolanttemp, bool mbmsfault, bool mthernalrunaway, int mdrive) const;
    };
    static void main__onStatus0InfoChanged_binding_slot(hmimain *self, bool mhvbattery, bool mcoolanttemp, bool mbmsfault, bool mthernalrunaway, int mdrive) { return main__onStatus0InfoChanged_bindingFunctor(self)(mhvbattery, mcoolanttemp, mbmsfault, mthernalrunaway, mdrive); }
    Qul::Private::Slot<hmimain, void(bool, bool, bool, bool, int)> main__onStatus0InfoChanged_binding;
    struct main__onChargeInfoChanged_bindingFunctor {
        hmimain *self;
        main__onChargeInfoChanged_bindingFunctor(hmimain *self_) : self(self_) {}
        void operator()(int mtime, int menergycon) const;
    };
    static void main__onChargeInfoChanged_binding_slot(hmimain *self, int mtime, int menergycon) { return main__onChargeInfoChanged_bindingFunctor(self)(mtime, menergycon); }
    Qul::Private::Slot<hmimain, void(int, int)> main__onChargeInfoChanged_binding;
    struct main__onAlertInfoChanged_bindingFunctor {
        hmimain *self;
        main__onAlertInfoChanged_bindingFunctor(hmimain *self_) : self(self_) {}
        void operator()(int mid, int mcode) const;
    };
    static void main__onAlertInfoChanged_binding_slot(hmimain *self, int mid, int mcode) { return main__onAlertInfoChanged_bindingFunctor(self)(mid, mcode); }
    Qul::Private::Slot<hmimain, void(int, int)> main__onAlertInfoChanged_binding;
    struct main__onBattInfoChanged_bindingFunctor {
        hmimain *self;
        main__onBattInfoChanged_bindingFunctor(hmimain *self_) : self(self_) {}
        void operator()(int msoc, int mrange, int mbattemp) const;
    };
    static void main__onBattInfoChanged_binding_slot(hmimain *self, int msoc, int mrange, int mbattemp) { return main__onBattInfoChanged_bindingFunctor(self)(msoc, mrange, mbattemp); }
    Qul::Private::Slot<hmimain, void(int, int, int)> main__onBattInfoChanged_binding;
    struct main__onMotorInfoChanged_bindingFunctor {
        hmimain *self;
        main__onMotorInfoChanged_bindingFunctor(hmimain *self_) : self(self_) {}
        void operator()(int mspeed, int modo, int mtrip) const;
    };
    static void main__onMotorInfoChanged_binding_slot(hmimain *self, int mspeed, int modo, int mtrip) { return main__onMotorInfoChanged_bindingFunctor(self)(mspeed, modo, mtrip); }
    Qul::Private::Slot<hmimain, void(int, int, int)> main__onMotorInfoChanged_binding;
    struct main_width_anchor_bindingFunctor {
    int operator()(hmimain *self) const;
};
    Qul::Private::Binding<main_width_anchor_bindingFunctor, 1> main_width_anchor_binding;
    struct main_height_anchor_bindingFunctor {
    int operator()(hmimain *self) const;
};
    Qul::Private::Binding<main_height_anchor_bindingFunctor, 1> main_height_anchor_binding;
    struct splashscreen_width_anchor_bindingFunctor {
    int operator()(hmimain *self) const;
};
    Qul::Private::Binding<splashscreen_width_anchor_bindingFunctor, 1> splashscreen_width_anchor_binding;
    struct splashscreen_height_anchor_bindingFunctor {
    int operator()(hmimain *self) const;
};
    Qul::Private::Binding<splashscreen_height_anchor_bindingFunctor, 1> splashscreen_height_anchor_binding;
    struct splashlogo_x_anchor_bindingFunctor {
    int operator()(hmimain *self) const;
};
    Qul::Private::Binding<splashlogo_x_anchor_bindingFunctor, 2> splashlogo_x_anchor_binding;
    struct splashlogo_y_anchor_bindingFunctor {
    int operator()(hmimain *self) const;
};
    Qul::Private::Binding<splashlogo_y_anchor_bindingFunctor, 2> splashlogo_y_anchor_binding;
    struct splashlogo_height_bindingFunctor {
        int operator()(hmimain *self) const;
    };
    Qul::Private::Binding<splashlogo_height_bindingFunctor, 0> splashlogo_height_binding;
    struct splashlogo_width_bindingFunctor {
        int operator()(hmimain *self) const;
    };
    Qul::Private::Binding<splashlogo_width_bindingFunctor, 0> splashlogo_width_binding;
    struct homescreen_width_anchor_bindingFunctor {
    int operator()(hmimain *self) const;
};
    Qul::Private::Binding<homescreen_width_anchor_bindingFunctor, 1> homescreen_width_anchor_binding;
    struct homescreen_height_anchor_bindingFunctor {
    int operator()(hmimain *self) const;
};
    Qul::Private::Binding<homescreen_height_anchor_bindingFunctor, 1> homescreen_height_anchor_binding;
    struct logo_height_bindingFunctor {
        int operator()(hmimain *self) const;
    };
    Qul::Private::Binding<logo_height_bindingFunctor, 0> logo_height_binding;
    struct logo_width_bindingFunctor {
        int operator()(hmimain *self) const;
    };
    Qul::Private::Binding<logo_width_bindingFunctor, 0> logo_width_binding;
    struct logo_x_anchor_bindingFunctor {
    int operator()(hmimain *self) const;
};
    Qul::Private::Binding<logo_x_anchor_bindingFunctor, 2> logo_x_anchor_binding;
    struct truckgreen_visible_bindingFunctor {
        bool operator()(hmimain *self) const;
    };
    Qul::Private::Binding<truckgreen_visible_bindingFunctor, 0> truckgreen_visible_binding;
    struct truckgreen_height_bindingFunctor {
        int operator()(hmimain *self) const;
    };
    Qul::Private::Binding<truckgreen_height_bindingFunctor, 0> truckgreen_height_binding;
    struct truckgreen_width_bindingFunctor {
        int operator()(hmimain *self) const;
    };
    Qul::Private::Binding<truckgreen_width_bindingFunctor, 0> truckgreen_width_binding;
    struct truckgreen_x_anchor_bindingFunctor {
    int operator()(hmimain *self) const;
};
    Qul::Private::Binding<truckgreen_x_anchor_bindingFunctor, 2> truckgreen_x_anchor_binding;
    struct truckgreen_y_anchor_bindingFunctor {
    int operator()(hmimain *self) const;
};
    Qul::Private::Binding<truckgreen_y_anchor_bindingFunctor, 2> truckgreen_y_anchor_binding;
    struct truckred_visible_bindingFunctor {
        bool operator()(hmimain *self) const;
    };
    Qul::Private::Binding<truckred_visible_bindingFunctor, 0> truckred_visible_binding;
    struct truckred_height_bindingFunctor {
        int operator()(hmimain *self) const;
    };
    Qul::Private::Binding<truckred_height_bindingFunctor, 0> truckred_height_binding;
    struct truckred_width_bindingFunctor {
        int operator()(hmimain *self) const;
    };
    Qul::Private::Binding<truckred_width_bindingFunctor, 0> truckred_width_binding;
    struct truckred_x_anchor_bindingFunctor {
    int operator()(hmimain *self) const;
};
    Qul::Private::Binding<truckred_x_anchor_bindingFunctor, 2> truckred_x_anchor_binding;
    struct truckred_y_anchor_bindingFunctor {
    int operator()(hmimain *self) const;
};
    Qul::Private::Binding<truckred_y_anchor_bindingFunctor, 2> truckred_y_anchor_binding;
    struct hillhold_visible_bindingFunctor {
        bool operator()(hmimain *self) const;
    };
    Qul::Private::Binding<hillhold_visible_bindingFunctor, 0> hillhold_visible_binding;
    struct hillhold_height_bindingFunctor {
        int operator()(hmimain *self) const;
    };
    Qul::Private::Binding<hillhold_height_bindingFunctor, 0> hillhold_height_binding;
    struct hillhold_width_bindingFunctor {
        int operator()(hmimain *self) const;
    };
    Qul::Private::Binding<hillhold_width_bindingFunctor, 0> hillhold_width_binding;
    struct consoletop_height_bindingFunctor {
        int operator()(hmimain *self) const;
    };
    Qul::Private::Binding<consoletop_height_bindingFunctor, 0> consoletop_height_binding;
    struct consoletop_width_bindingFunctor {
        int operator()(hmimain *self) const;
    };
    Qul::Private::Binding<consoletop_width_bindingFunctor, 0> consoletop_width_binding;
    struct consoletop_x_anchor_bindingFunctor {
    int operator()(hmimain *self) const;
};
    Qul::Private::Binding<consoletop_x_anchor_bindingFunctor, 2> consoletop_x_anchor_binding;
    struct consolebottom_height_bindingFunctor {
        int operator()(hmimain *self) const;
    };
    Qul::Private::Binding<consolebottom_height_bindingFunctor, 0> consolebottom_height_binding;
    struct consolebottom_width_bindingFunctor {
        int operator()(hmimain *self) const;
    };
    Qul::Private::Binding<consolebottom_width_bindingFunctor, 0> consolebottom_width_binding;
    struct consolebottom_x_anchor_bindingFunctor {
    int operator()(hmimain *self) const;
};
    Qul::Private::Binding<consolebottom_x_anchor_bindingFunctor, 2> consolebottom_x_anchor_binding;
    struct consolebottom_y_anchor_bindingFunctor {
    int operator()(hmimain *self) const;
};
    Qul::Private::Binding<consolebottom_y_anchor_bindingFunctor, 2> consolebottom_y_anchor_binding;
    struct drive_opacity_bindingFunctor {
        Qul::qreal operator()(hmimain *self) const;
    };
    Qul::Private::Binding<drive_opacity_bindingFunctor, 0> drive_opacity_binding;
    struct drive_height_bindingFunctor {
        int operator()(hmimain *self) const;
    };
    Qul::Private::Binding<drive_height_bindingFunctor, 0> drive_height_binding;
    struct drive_width_bindingFunctor {
        int operator()(hmimain *self) const;
    };
    Qul::Private::Binding<drive_width_bindingFunctor, 0> drive_width_binding;
    struct drive_x_anchor_bindingFunctor {
    int operator()(hmimain *self) const;
};
    Qul::Private::Binding<drive_x_anchor_bindingFunctor, 3> drive_x_anchor_binding;
    struct drive_y_anchor_bindingFunctor {
    int operator()(hmimain *self) const;
};
    Qul::Private::Binding<drive_y_anchor_bindingFunctor, 3> drive_y_anchor_binding;
    struct reverse_opacity_bindingFunctor {
        Qul::qreal operator()(hmimain *self) const;
    };
    Qul::Private::Binding<reverse_opacity_bindingFunctor, 0> reverse_opacity_binding;
    struct reverse_height_bindingFunctor {
        int operator()(hmimain *self) const;
    };
    Qul::Private::Binding<reverse_height_bindingFunctor, 0> reverse_height_binding;
    struct reverse_width_bindingFunctor {
        int operator()(hmimain *self) const;
    };
    Qul::Private::Binding<reverse_width_bindingFunctor, 0> reverse_width_binding;
    struct reverse_x_anchor_bindingFunctor {
    int operator()(hmimain *self) const;
};
    Qul::Private::Binding<reverse_x_anchor_bindingFunctor, 2> reverse_x_anchor_binding;
    struct reverse_y_anchor_bindingFunctor {
    int operator()(hmimain *self) const;
};
    Qul::Private::Binding<reverse_y_anchor_bindingFunctor, 1> reverse_y_anchor_binding;
    struct neutral_opacity_bindingFunctor {
        Qul::qreal operator()(hmimain *self) const;
    };
    Qul::Private::Binding<neutral_opacity_bindingFunctor, 0> neutral_opacity_binding;
    struct neutral_height_bindingFunctor {
        int operator()(hmimain *self) const;
    };
    Qul::Private::Binding<neutral_height_bindingFunctor, 0> neutral_height_binding;
    struct neutral_width_bindingFunctor {
        int operator()(hmimain *self) const;
    };
    Qul::Private::Binding<neutral_width_bindingFunctor, 0> neutral_width_binding;
    struct neutral_x_anchor_bindingFunctor {
    int operator()(hmimain *self) const;
};
    Qul::Private::Binding<neutral_x_anchor_bindingFunctor, 2> neutral_x_anchor_binding;
    struct neutral_y_anchor_bindingFunctor {
    int operator()(hmimain *self) const;
};
    Qul::Private::Binding<neutral_y_anchor_bindingFunctor, 1> neutral_y_anchor_binding;
    struct sport_opacity_bindingFunctor {
        Qul::qreal operator()(hmimain *self) const;
    };
    Qul::Private::Binding<sport_opacity_bindingFunctor, 0> sport_opacity_binding;
    struct sport_height_bindingFunctor {
        int operator()(hmimain *self) const;
    };
    Qul::Private::Binding<sport_height_bindingFunctor, 0> sport_height_binding;
    struct sport_width_bindingFunctor {
        int operator()(hmimain *self) const;
    };
    Qul::Private::Binding<sport_width_bindingFunctor, 0> sport_width_binding;
    struct sport_x_anchor_bindingFunctor {
    int operator()(hmimain *self) const;
};
    Qul::Private::Binding<sport_x_anchor_bindingFunctor, 2> sport_x_anchor_binding;
    struct sport_y_anchor_bindingFunctor {
    int operator()(hmimain *self) const;
};
    Qul::Private::Binding<sport_y_anchor_bindingFunctor, 1> sport_y_anchor_binding;
    struct hbeam_visible_bindingFunctor {
        bool operator()(hmimain *self) const;
    };
    Qul::Private::Binding<hbeam_visible_bindingFunctor, 0> hbeam_visible_binding;
    struct hbeam_height_bindingFunctor {
        int operator()(hmimain *self) const;
    };
    Qul::Private::Binding<hbeam_height_bindingFunctor, 0> hbeam_height_binding;
    struct hbeam_width_bindingFunctor {
        int operator()(hmimain *self) const;
    };
    Qul::Private::Binding<hbeam_width_bindingFunctor, 0> hbeam_width_binding;
    struct hbeam_x_anchor_bindingFunctor {
    int operator()(hmimain *self) const;
};
    Qul::Private::Binding<hbeam_x_anchor_bindingFunctor, 2> hbeam_x_anchor_binding;
    struct lbeam_visible_bindingFunctor {
        bool operator()(hmimain *self) const;
    };
    Qul::Private::Binding<lbeam_visible_bindingFunctor, 0> lbeam_visible_binding;
    struct lbeam_height_bindingFunctor {
        int operator()(hmimain *self) const;
    };
    Qul::Private::Binding<lbeam_height_bindingFunctor, 0> lbeam_height_binding;
    struct lbeam_width_bindingFunctor {
        int operator()(hmimain *self) const;
    };
    Qul::Private::Binding<lbeam_width_bindingFunctor, 0> lbeam_width_binding;
    struct lbeam_x_anchor_bindingFunctor {
    int operator()(hmimain *self) const;
};
    Qul::Private::Binding<lbeam_x_anchor_bindingFunctor, 2> lbeam_x_anchor_binding;
    struct breakfault_visible_bindingFunctor {
        bool operator()(hmimain *self) const;
    };
    Qul::Private::Binding<breakfault_visible_bindingFunctor, 0> breakfault_visible_binding;
    struct breakfault_height_bindingFunctor {
        int operator()(hmimain *self) const;
    };
    Qul::Private::Binding<breakfault_height_bindingFunctor, 0> breakfault_height_binding;
    struct breakfault_width_bindingFunctor {
        int operator()(hmimain *self) const;
    };
    Qul::Private::Binding<breakfault_width_bindingFunctor, 0> breakfault_width_binding;
    struct seatbelt_visible_bindingFunctor {
        bool operator()(hmimain *self) const;
    };
    Qul::Private::Binding<seatbelt_visible_bindingFunctor, 0> seatbelt_visible_binding;
    struct seatbelt_height_bindingFunctor {
        int operator()(hmimain *self) const;
    };
    Qul::Private::Binding<seatbelt_height_bindingFunctor, 0> seatbelt_height_binding;
    struct seatbelt_width_bindingFunctor {
        int operator()(hmimain *self) const;
    };
    Qul::Private::Binding<seatbelt_width_bindingFunctor, 0> seatbelt_width_binding;
    struct seatbelt_x_anchor_bindingFunctor {
    int operator()(hmimain *self) const;
};
    Qul::Private::Binding<seatbelt_x_anchor_bindingFunctor, 2> seatbelt_x_anchor_binding;
    struct airbag_visible_bindingFunctor {
        bool operator()(hmimain *self) const;
    };
    Qul::Private::Binding<airbag_visible_bindingFunctor, 0> airbag_visible_binding;
    struct airbag_height_bindingFunctor {
        int operator()(hmimain *self) const;
    };
    Qul::Private::Binding<airbag_height_bindingFunctor, 0> airbag_height_binding;
    struct airbag_width_bindingFunctor {
        int operator()(hmimain *self) const;
    };
    Qul::Private::Binding<airbag_width_bindingFunctor, 0> airbag_width_binding;
    struct airbag_x_anchor_bindingFunctor {
    int operator()(hmimain *self) const;
};
    Qul::Private::Binding<airbag_x_anchor_bindingFunctor, 2> airbag_x_anchor_binding;
    struct lowcoolant_visible_bindingFunctor {
        bool operator()(hmimain *self) const;
    };
    Qul::Private::Binding<lowcoolant_visible_bindingFunctor, 0> lowcoolant_visible_binding;
    struct lowcoolant_height_bindingFunctor {
        int operator()(hmimain *self) const;
    };
    Qul::Private::Binding<lowcoolant_height_bindingFunctor, 0> lowcoolant_height_binding;
    struct lowcoolant_width_bindingFunctor {
        int operator()(hmimain *self) const;
    };
    Qul::Private::Binding<lowcoolant_width_bindingFunctor, 0> lowcoolant_width_binding;
    struct lowcoolant_x_anchor_bindingFunctor {
    int operator()(hmimain *self) const;
};
    Qul::Private::Binding<lowcoolant_x_anchor_bindingFunctor, 2> lowcoolant_x_anchor_binding;
    struct indfrontfog_visible_bindingFunctor {
        bool operator()(hmimain *self) const;
    };
    Qul::Private::Binding<indfrontfog_visible_bindingFunctor, 0> indfrontfog_visible_binding;
    struct indfrontfog_height_bindingFunctor {
        int operator()(hmimain *self) const;
    };
    Qul::Private::Binding<indfrontfog_height_bindingFunctor, 0> indfrontfog_height_binding;
    struct indfrontfog_width_bindingFunctor {
        int operator()(hmimain *self) const;
    };
    Qul::Private::Binding<indfrontfog_width_bindingFunctor, 0> indfrontfog_width_binding;
    struct indfrontfog_x_anchor_bindingFunctor {
    int operator()(hmimain *self) const;
};
    Qul::Private::Binding<indfrontfog_x_anchor_bindingFunctor, 2> indfrontfog_x_anchor_binding;
    struct positionlights_visible_bindingFunctor {
        bool operator()(hmimain *self) const;
    };
    Qul::Private::Binding<positionlights_visible_bindingFunctor, 0> positionlights_visible_binding;
    struct positionlights_height_bindingFunctor {
        int operator()(hmimain *self) const;
    };
    Qul::Private::Binding<positionlights_height_bindingFunctor, 0> positionlights_height_binding;
    struct positionlights_width_bindingFunctor {
        int operator()(hmimain *self) const;
    };
    Qul::Private::Binding<positionlights_width_bindingFunctor, 0> positionlights_width_binding;
    struct positionlights_x_anchor_bindingFunctor {
    int operator()(hmimain *self) const;
};
    Qul::Private::Binding<positionlights_x_anchor_bindingFunctor, 2> positionlights_x_anchor_binding;
    struct limphome_visible_bindingFunctor {
        bool operator()(hmimain *self) const;
    };
    Qul::Private::Binding<limphome_visible_bindingFunctor, 0> limphome_visible_binding;
    struct limphome_height_bindingFunctor {
        int operator()(hmimain *self) const;
    };
    Qul::Private::Binding<limphome_height_bindingFunctor, 0> limphome_height_binding;
    struct limphome_width_bindingFunctor {
        int operator()(hmimain *self) const;
    };
    Qul::Private::Binding<limphome_width_bindingFunctor, 0> limphome_width_binding;
    struct limphome_x_anchor_bindingFunctor {
    int operator()(hmimain *self) const;
};
    Qul::Private::Binding<limphome_x_anchor_bindingFunctor, 2> limphome_x_anchor_binding;
    struct indsteering_height_bindingFunctor {
        int operator()(hmimain *self) const;
    };
    Qul::Private::Binding<indsteering_height_bindingFunctor, 0> indsteering_height_binding;
    struct indsteering_width_bindingFunctor {
        int operator()(hmimain *self) const;
    };
    Qul::Private::Binding<indsteering_width_bindingFunctor, 0> indsteering_width_binding;
    struct indsteering_y_anchor_bindingFunctor {
    int operator()(hmimain *self) const;
};
    Qul::Private::Binding<indsteering_y_anchor_bindingFunctor, 2> indsteering_y_anchor_binding;
    struct dooropen_visible_bindingFunctor {
        bool operator()(hmimain *self) const;
    };
    Qul::Private::Binding<dooropen_visible_bindingFunctor, 0> dooropen_visible_binding;
    struct dooropen_height_bindingFunctor {
        int operator()(hmimain *self) const;
    };
    Qul::Private::Binding<dooropen_height_bindingFunctor, 0> dooropen_height_binding;
    struct dooropen_width_bindingFunctor {
        int operator()(hmimain *self) const;
    };
    Qul::Private::Binding<dooropen_width_bindingFunctor, 0> dooropen_width_binding;
    struct dooropen_y_anchor_bindingFunctor {
    int operator()(hmimain *self) const;
};
    Qul::Private::Binding<dooropen_y_anchor_bindingFunctor, 2> dooropen_y_anchor_binding;
    struct hvbattery_visible_bindingFunctor {
        bool operator()(hmimain *self) const;
    };
    Qul::Private::Binding<hvbattery_visible_bindingFunctor, 0> hvbattery_visible_binding;
    struct hvbattery_height_bindingFunctor {
        int operator()(hmimain *self) const;
    };
    Qul::Private::Binding<hvbattery_height_bindingFunctor, 0> hvbattery_height_binding;
    struct hvbattery_width_bindingFunctor {
        int operator()(hmimain *self) const;
    };
    Qul::Private::Binding<hvbattery_width_bindingFunctor, 0> hvbattery_width_binding;
    struct hvbattery_y_anchor_bindingFunctor {
    int operator()(hmimain *self) const;
};
    Qul::Private::Binding<hvbattery_y_anchor_bindingFunctor, 2> hvbattery_y_anchor_binding;
    struct serviceDisconnect_visible_bindingFunctor {
        bool operator()(hmimain *self) const;
    };
    Qul::Private::Binding<serviceDisconnect_visible_bindingFunctor, 0> serviceDisconnect_visible_binding;
    struct serviceDisconnect_height_bindingFunctor {
        int operator()(hmimain *self) const;
    };
    Qul::Private::Binding<serviceDisconnect_height_bindingFunctor, 0> serviceDisconnect_height_binding;
    struct serviceDisconnect_width_bindingFunctor {
        int operator()(hmimain *self) const;
    };
    Qul::Private::Binding<serviceDisconnect_width_bindingFunctor, 0> serviceDisconnect_width_binding;
    struct serviceDisconnect_y_anchor_bindingFunctor {
    int operator()(hmimain *self) const;
};
    Qul::Private::Binding<serviceDisconnect_y_anchor_bindingFunctor, 2> serviceDisconnect_y_anchor_binding;
    struct coolanttemp_visible_bindingFunctor {
        bool operator()(hmimain *self) const;
    };
    Qul::Private::Binding<coolanttemp_visible_bindingFunctor, 0> coolanttemp_visible_binding;
    struct coolanttemp_height_bindingFunctor {
        int operator()(hmimain *self) const;
    };
    Qul::Private::Binding<coolanttemp_height_bindingFunctor, 0> coolanttemp_height_binding;
    struct coolanttemp_width_bindingFunctor {
        int operator()(hmimain *self) const;
    };
    Qul::Private::Binding<coolanttemp_width_bindingFunctor, 0> coolanttemp_width_binding;
    struct coolanttemp_y_anchor_bindingFunctor {
    int operator()(hmimain *self) const;
};
    Qul::Private::Binding<coolanttemp_y_anchor_bindingFunctor, 2> coolanttemp_y_anchor_binding;
    struct indright_visible_bindingFunctor {
        bool operator()(hmimain *self) const;
    };
    Qul::Private::Binding<indright_visible_bindingFunctor, 0> indright_visible_binding;
    struct indright_height_bindingFunctor {
        int operator()(hmimain *self) const;
    };
    Qul::Private::Binding<indright_height_bindingFunctor, 0> indright_height_binding;
    struct indright_width_bindingFunctor {
        int operator()(hmimain *self) const;
    };
    Qul::Private::Binding<indright_width_bindingFunctor, 0> indright_width_binding;
    struct indright_x_anchor_bindingFunctor {
    int operator()(hmimain *self) const;
};
    Qul::Private::Binding<indright_x_anchor_bindingFunctor, 2> indright_x_anchor_binding;
    struct indleft_visible_bindingFunctor {
        bool operator()(hmimain *self) const;
    };
    Qul::Private::Binding<indleft_visible_bindingFunctor, 0> indleft_visible_binding;
    struct indleft_height_bindingFunctor {
        int operator()(hmimain *self) const;
    };
    Qul::Private::Binding<indleft_height_bindingFunctor, 0> indleft_height_binding;
    struct indleft_width_bindingFunctor {
        int operator()(hmimain *self) const;
    };
    Qul::Private::Binding<indleft_width_bindingFunctor, 0> indleft_width_binding;
    struct speedText_x_anchor_bindingFunctor {
    int operator()(hmimain *self) const;
};
    Qul::Private::Binding<speedText_x_anchor_bindingFunctor, 3> speedText_x_anchor_binding;
    struct speedText_y_anchor_bindingFunctor {
    int operator()(hmimain *self) const;
};
    Qul::Private::Binding<speedText_y_anchor_bindingFunctor, 1> speedText_y_anchor_binding;
    struct speedText_color_bindingFunctor {
        Qul::PlatformInterface::Rgba32 operator()(hmimain *self) const;
    };
    Qul::Private::Binding<speedText_color_bindingFunctor, 0> speedText_color_binding;
    struct speedText_text_bindingFunctor {
        Qul::Private::String operator()(hmimain *self) const;
    };
    Qul::Private::Binding<speedText_text_bindingFunctor, 0> speedText_text_binding;
    struct kmph_x_anchor_bindingFunctor {
    int operator()(hmimain *self) const;
};
    Qul::Private::Binding<kmph_x_anchor_bindingFunctor, 1> kmph_x_anchor_binding;
    struct kmph_y_anchor_bindingFunctor {
    int operator()(hmimain *self) const;
};
    Qul::Private::Binding<kmph_y_anchor_bindingFunctor, 2> kmph_y_anchor_binding;
    struct rectangle_x_anchor_bindingFunctor {
    int operator()(hmimain *self) const;
};
    Qul::Private::Binding<rectangle_x_anchor_bindingFunctor, 3> rectangle_x_anchor_binding;
    struct rectangle_y_anchor_bindingFunctor {
    int operator()(hmimain *self) const;
};
    Qul::Private::Binding<rectangle_y_anchor_bindingFunctor, 2> rectangle_y_anchor_binding;
    struct row_x_anchor_bindingFunctor {
    int operator()(hmimain *self) const;
};
    Qul::Private::Binding<row_x_anchor_bindingFunctor, 2> row_x_anchor_binding;
    struct row_y_anchor_bindingFunctor {
    int operator()(hmimain *self) const;
};
    Qul::Private::Binding<row_y_anchor_bindingFunctor, 2> row_y_anchor_binding;
    struct odoval_text_bindingFunctor {
        Qul::Private::String operator()(hmimain *self) const;
    };
    Qul::Private::Binding<odoval_text_bindingFunctor, 0> odoval_text_binding;
    struct rectangle_2_x_anchor_bindingFunctor {
    int operator()(hmimain *self) const;
};
    Qul::Private::Binding<rectangle_2_x_anchor_bindingFunctor, 3> rectangle_2_x_anchor_binding;
    struct rectangle_2_y_anchor_bindingFunctor {
    int operator()(hmimain *self) const;
};
    Qul::Private::Binding<rectangle_2_y_anchor_bindingFunctor, 2> rectangle_2_y_anchor_binding;
    struct row_2_x_anchor_bindingFunctor {
    int operator()(hmimain *self) const;
};
    Qul::Private::Binding<row_2_x_anchor_bindingFunctor, 2> row_2_x_anchor_binding;
    struct row_2_y_anchor_bindingFunctor {
    int operator()(hmimain *self) const;
};
    Qul::Private::Binding<row_2_y_anchor_bindingFunctor, 2> row_2_y_anchor_binding;
    struct tripval_text_bindingFunctor {
        Qul::Private::String operator()(hmimain *self) const;
    };
    Qul::Private::Binding<tripval_text_bindingFunctor, 0> tripval_text_binding;
    struct iconmaxspeed_visible_bindingFunctor {
        bool operator()(hmimain *self) const;
    };
    Qul::Private::Binding<iconmaxspeed_visible_bindingFunctor, 0> iconmaxspeed_visible_binding;
    struct iconmaxspeed_height_bindingFunctor {
        int operator()(hmimain *self) const;
    };
    Qul::Private::Binding<iconmaxspeed_height_bindingFunctor, 0> iconmaxspeed_height_binding;
    struct iconmaxspeed_width_bindingFunctor {
        int operator()(hmimain *self) const;
    };
    Qul::Private::Binding<iconmaxspeed_width_bindingFunctor, 0> iconmaxspeed_width_binding;
    struct iconmaxspeed_x_anchor_bindingFunctor {
    int operator()(hmimain *self) const;
};
    Qul::Private::Binding<iconmaxspeed_x_anchor_bindingFunctor, 2> iconmaxspeed_x_anchor_binding;
    struct iconmaxspeed_y_anchor_bindingFunctor {
    int operator()(hmimain *self) const;
};
    Qul::Private::Binding<iconmaxspeed_y_anchor_bindingFunctor, 2> iconmaxspeed_y_anchor_binding;
    struct iconlowsoc_visible_bindingFunctor {
        bool operator()(hmimain *self) const;
    };
    Qul::Private::Binding<iconlowsoc_visible_bindingFunctor, 0> iconlowsoc_visible_binding;
    struct iconlowsoc_height_bindingFunctor {
        int operator()(hmimain *self) const;
    };
    Qul::Private::Binding<iconlowsoc_height_bindingFunctor, 0> iconlowsoc_height_binding;
    struct iconlowsoc_width_bindingFunctor {
        int operator()(hmimain *self) const;
    };
    Qul::Private::Binding<iconlowsoc_width_bindingFunctor, 0> iconlowsoc_width_binding;
    struct iconlowsoc_x_anchor_bindingFunctor {
    int operator()(hmimain *self) const;
};
    Qul::Private::Binding<iconlowsoc_x_anchor_bindingFunctor, 2> iconlowsoc_x_anchor_binding;
    struct iconlowsoc_y_anchor_bindingFunctor {
    int operator()(hmimain *self) const;
};
    Qul::Private::Binding<iconlowsoc_y_anchor_bindingFunctor, 3> iconlowsoc_y_anchor_binding;
    struct iconregen_visible_bindingFunctor {
        bool operator()(hmimain *self) const;
    };
    Qul::Private::Binding<iconregen_visible_bindingFunctor, 0> iconregen_visible_binding;
    struct iconregen_height_bindingFunctor {
        int operator()(hmimain *self) const;
    };
    Qul::Private::Binding<iconregen_height_bindingFunctor, 0> iconregen_height_binding;
    struct iconregen_width_bindingFunctor {
        int operator()(hmimain *self) const;
    };
    Qul::Private::Binding<iconregen_width_bindingFunctor, 0> iconregen_width_binding;
    struct iconregen_x_anchor_bindingFunctor {
    int operator()(hmimain *self) const;
};
    Qul::Private::Binding<iconregen_x_anchor_bindingFunctor, 2> iconregen_x_anchor_binding;
    struct iconregen_y_anchor_bindingFunctor {
    int operator()(hmimain *self) const;
};
    Qul::Private::Binding<iconregen_y_anchor_bindingFunctor, 1> iconregen_y_anchor_binding;
    struct bgbattery_height_bindingFunctor {
        int operator()(hmimain *self) const;
    };
    Qul::Private::Binding<bgbattery_height_bindingFunctor, 0> bgbattery_height_binding;
    struct bgbattery_width_bindingFunctor {
        int operator()(hmimain *self) const;
    };
    Qul::Private::Binding<bgbattery_width_bindingFunctor, 0> bgbattery_width_binding;
    struct bgbattery_x_anchor_bindingFunctor {
    int operator()(hmimain *self) const;
};
    Qul::Private::Binding<bgbattery_x_anchor_bindingFunctor, 1> bgbattery_x_anchor_binding;
    struct bgbattery_y_anchor_bindingFunctor {
    int operator()(hmimain *self) const;
};
    Qul::Private::Binding<bgbattery_y_anchor_bindingFunctor, 3> bgbattery_y_anchor_binding;
    struct batterybar_x_anchor_bindingFunctor {
    int operator()(hmimain *self) const;
};
    Qul::Private::Binding<batterybar_x_anchor_bindingFunctor, 1> batterybar_x_anchor_binding;
    struct batterybar_y_anchor_bindingFunctor {
    int operator()(hmimain *self) const;
};
    Qul::Private::Binding<batterybar_y_anchor_bindingFunctor, 2> batterybar_y_anchor_binding;
    struct rectangle_3_y_anchor_bindingFunctor {
    int operator()(hmimain *self) const;
};
    Qul::Private::Binding<rectangle_3_y_anchor_bindingFunctor, 2> rectangle_3_y_anchor_binding;
    struct rectangle_3_height_bindingFunctor {
        int operator()(hmimain *self) const;
    };
    Qul::Private::Binding<rectangle_3_height_bindingFunctor, 0> rectangle_3_height_binding;
    struct rectangle_3_width_bindingFunctor {
        int operator()(hmimain *self) const;
    };
    Qul::Private::Binding<rectangle_3_width_bindingFunctor, 0> rectangle_3_width_binding;
    struct rectangle_4_y_anchor_bindingFunctor {
    int operator()(hmimain *self) const;
};
    Qul::Private::Binding<rectangle_4_y_anchor_bindingFunctor, 2> rectangle_4_y_anchor_binding;
    struct rectangle_4_color_bindingFunctor {
        Qul::PlatformInterface::Rgba32 operator()(hmimain *self) const;
    };
    Qul::Private::Binding<rectangle_4_color_bindingFunctor, 0> rectangle_4_color_binding;
    struct rectangle_4_height_bindingFunctor {
        int operator()(hmimain *self) const;
    };
    Qul::Private::Binding<rectangle_4_height_bindingFunctor, 0> rectangle_4_height_binding;
    struct rectangle_4_width_bindingFunctor {
        int operator()(hmimain *self) const;
    };
    Qul::Private::Binding<rectangle_4_width_bindingFunctor, 0> rectangle_4_width_binding;
    struct rectangle_5_x_anchor_bindingFunctor {
    int operator()(hmimain *self) const;
};
    Qul::Private::Binding<rectangle_5_x_anchor_bindingFunctor, 2> rectangle_5_x_anchor_binding;
    struct rectangle_5_y_anchor_bindingFunctor {
    int operator()(hmimain *self) const;
};
    Qul::Private::Binding<rectangle_5_y_anchor_bindingFunctor, 3> rectangle_5_y_anchor_binding;
    struct rectangle_5_height_bindingFunctor {
        int operator()(hmimain *self) const;
    };
    Qul::Private::Binding<rectangle_5_height_bindingFunctor, 0> rectangle_5_height_binding;
    struct rectangle_6_x_anchor_bindingFunctor {
    int operator()(hmimain *self) const;
};
    Qul::Private::Binding<rectangle_6_x_anchor_bindingFunctor, 3> rectangle_6_x_anchor_binding;
    struct rectangle_6_y_anchor_bindingFunctor {
    int operator()(hmimain *self) const;
};
    Qul::Private::Binding<rectangle_6_y_anchor_bindingFunctor, 3> rectangle_6_y_anchor_binding;
    struct row_3_x_anchor_bindingFunctor {
    int operator()(hmimain *self) const;
};
    Qul::Private::Binding<row_3_x_anchor_bindingFunctor, 2> row_3_x_anchor_binding;
    struct row_3_y_anchor_bindingFunctor {
    int operator()(hmimain *self) const;
};
    Qul::Private::Binding<row_3_y_anchor_bindingFunctor, 2> row_3_y_anchor_binding;
    struct batper_text_bindingFunctor {
        Qul::Private::String operator()(hmimain *self) const;
    };
    Qul::Private::Binding<batper_text_bindingFunctor, 0> batper_text_binding;
    struct bgrange_height_bindingFunctor {
        int operator()(hmimain *self) const;
    };
    Qul::Private::Binding<bgrange_height_bindingFunctor, 0> bgrange_height_binding;
    struct bgrange_width_bindingFunctor {
        int operator()(hmimain *self) const;
    };
    Qul::Private::Binding<bgrange_width_bindingFunctor, 0> bgrange_width_binding;
    struct bgrange_x_anchor_bindingFunctor {
    int operator()(hmimain *self) const;
};
    Qul::Private::Binding<bgrange_x_anchor_bindingFunctor, 2> bgrange_x_anchor_binding;
    struct bgrange_y_anchor_bindingFunctor {
    int operator()(hmimain *self) const;
};
    Qul::Private::Binding<bgrange_y_anchor_bindingFunctor, 3> bgrange_y_anchor_binding;
    struct rangename_x_anchor_bindingFunctor {
    int operator()(hmimain *self) const;
};
    Qul::Private::Binding<rangename_x_anchor_bindingFunctor, 3> rangename_x_anchor_binding;
    struct rangename_y_anchor_bindingFunctor {
    int operator()(hmimain *self) const;
};
    Qul::Private::Binding<rangename_y_anchor_bindingFunctor, 1> rangename_y_anchor_binding;
    struct rectangle_7_x_anchor_bindingFunctor {
    int operator()(hmimain *self) const;
};
    Qul::Private::Binding<rectangle_7_x_anchor_bindingFunctor, 3> rectangle_7_x_anchor_binding;
    struct rectangle_7_y_anchor_bindingFunctor {
    int operator()(hmimain *self) const;
};
    Qul::Private::Binding<rectangle_7_y_anchor_bindingFunctor, 2> rectangle_7_y_anchor_binding;
    struct row_4_x_anchor_bindingFunctor {
    int operator()(hmimain *self) const;
};
    Qul::Private::Binding<row_4_x_anchor_bindingFunctor, 2> row_4_x_anchor_binding;
    struct row_4_y_anchor_bindingFunctor {
    int operator()(hmimain *self) const;
};
    Qul::Private::Binding<row_4_y_anchor_bindingFunctor, 2> row_4_y_anchor_binding;
    struct rangeval_text_bindingFunctor {
        Qul::Private::String operator()(hmimain *self) const;
    };
    Qul::Private::Binding<rangeval_text_bindingFunctor, 0> rangeval_text_binding;
    struct chargescreen_width_anchor_bindingFunctor {
    int operator()(hmimain *self) const;
};
    Qul::Private::Binding<chargescreen_width_anchor_bindingFunctor, 1> chargescreen_width_anchor_binding;
    struct chargescreen_height_anchor_bindingFunctor {
    int operator()(hmimain *self) const;
};
    Qul::Private::Binding<chargescreen_height_anchor_bindingFunctor, 1> chargescreen_height_anchor_binding;
    struct bgcharge_x_anchor_bindingFunctor {
    int operator()(hmimain *self) const;
};
    Qul::Private::Binding<bgcharge_x_anchor_bindingFunctor, 2> bgcharge_x_anchor_binding;
    struct bgcharge_y_anchor_bindingFunctor {
    int operator()(hmimain *self) const;
};
    Qul::Private::Binding<bgcharge_y_anchor_bindingFunctor, 2> bgcharge_y_anchor_binding;
    struct bgcharge_height_bindingFunctor {
        int operator()(hmimain *self) const;
    };
    Qul::Private::Binding<bgcharge_height_bindingFunctor, 0> bgcharge_height_binding;
    struct bgcharge_width_bindingFunctor {
        int operator()(hmimain *self) const;
    };
    Qul::Private::Binding<bgcharge_width_bindingFunctor, 0> bgcharge_width_binding;
    struct rectangle_8_y_anchor_bindingFunctor {
    int operator()(hmimain *self) const;
};
    Qul::Private::Binding<rectangle_8_y_anchor_bindingFunctor, 2> rectangle_8_y_anchor_binding;
    struct rectangle_8_height_bindingFunctor {
        int operator()(hmimain *self) const;
    };
    Qul::Private::Binding<rectangle_8_height_bindingFunctor, 0> rectangle_8_height_binding;
    struct rectangle_8_width_bindingFunctor {
        int operator()(hmimain *self) const;
    };
    Qul::Private::Binding<rectangle_8_width_bindingFunctor, 0> rectangle_8_width_binding;
    struct rectangle_9_y_anchor_bindingFunctor {
    int operator()(hmimain *self) const;
};
    Qul::Private::Binding<rectangle_9_y_anchor_bindingFunctor, 2> rectangle_9_y_anchor_binding;
    struct rectangle_9_color_bindingFunctor {
        Qul::PlatformInterface::Rgba32 operator()(hmimain *self) const;
    };
    Qul::Private::Binding<rectangle_9_color_bindingFunctor, 0> rectangle_9_color_binding;
    struct rectangle_9_height_bindingFunctor {
        int operator()(hmimain *self) const;
    };
    Qul::Private::Binding<rectangle_9_height_bindingFunctor, 0> rectangle_9_height_binding;
    struct rectangle_9_width_bindingFunctor {
        int operator()(hmimain *self) const;
    };
    Qul::Private::Binding<rectangle_9_width_bindingFunctor, 0> rectangle_9_width_binding;
    struct rectangle_10_x_anchor_bindingFunctor {
    int operator()(hmimain *self) const;
};
    Qul::Private::Binding<rectangle_10_x_anchor_bindingFunctor, 2> rectangle_10_x_anchor_binding;
    struct rectangle_10_y_anchor_bindingFunctor {
    int operator()(hmimain *self) const;
};
    Qul::Private::Binding<rectangle_10_y_anchor_bindingFunctor, 3> rectangle_10_y_anchor_binding;
    struct rectangle_10_height_bindingFunctor {
        int operator()(hmimain *self) const;
    };
    Qul::Private::Binding<rectangle_10_height_bindingFunctor, 0> rectangle_10_height_binding;
    struct rectangle_11_x_anchor_bindingFunctor {
    int operator()(hmimain *self) const;
};
    Qul::Private::Binding<rectangle_11_x_anchor_bindingFunctor, 3> rectangle_11_x_anchor_binding;
    struct rectangle_11_y_anchor_bindingFunctor {
    int operator()(hmimain *self) const;
};
    Qul::Private::Binding<rectangle_11_y_anchor_bindingFunctor, 3> rectangle_11_y_anchor_binding;
    struct row_5_x_anchor_bindingFunctor {
    int operator()(hmimain *self) const;
};
    Qul::Private::Binding<row_5_x_anchor_bindingFunctor, 2> row_5_x_anchor_binding;
    struct row_5_y_anchor_bindingFunctor {
    int operator()(hmimain *self) const;
};
    Qul::Private::Binding<row_5_y_anchor_bindingFunctor, 2> row_5_y_anchor_binding;
    struct chargebatper_text_bindingFunctor {
        Qul::Private::String operator()(hmimain *self) const;
    };
    Qul::Private::Binding<chargebatper_text_bindingFunctor, 0> chargebatper_text_binding;
    struct idchargeicon_visible_bindingFunctor {
        bool operator()(hmimain *self) const;
    };
    Qul::Private::Binding<idchargeicon_visible_bindingFunctor, 0> idchargeicon_visible_binding;
    struct idchargeicon_height_bindingFunctor {
        int operator()(hmimain *self) const;
    };
    Qul::Private::Binding<idchargeicon_height_bindingFunctor, 0> idchargeicon_height_binding;
    struct idchargeicon_width_bindingFunctor {
        int operator()(hmimain *self) const;
    };
    Qul::Private::Binding<idchargeicon_width_bindingFunctor, 0> idchargeicon_width_binding;
    struct idchargeicon_x_anchor_bindingFunctor {
    int operator()(hmimain *self) const;
};
    Qul::Private::Binding<idchargeicon_x_anchor_bindingFunctor, 2> idchargeicon_x_anchor_binding;
    struct idchargeicon_y_anchor_bindingFunctor {
    int operator()(hmimain *self) const;
};
    Qul::Private::Binding<idchargeicon_y_anchor_bindingFunctor, 2> idchargeicon_y_anchor_binding;
    struct idchargecomp_visible_bindingFunctor {
        bool operator()(hmimain *self) const;
    };
    Qul::Private::Binding<idchargecomp_visible_bindingFunctor, 0> idchargecomp_visible_binding;
    struct idchargecomp_height_bindingFunctor {
        int operator()(hmimain *self) const;
    };
    Qul::Private::Binding<idchargecomp_height_bindingFunctor, 0> idchargecomp_height_binding;
    struct idchargecomp_width_bindingFunctor {
        int operator()(hmimain *self) const;
    };
    Qul::Private::Binding<idchargecomp_width_bindingFunctor, 0> idchargecomp_width_binding;
    struct idchargecomp_x_anchor_bindingFunctor {
    int operator()(hmimain *self) const;
};
    Qul::Private::Binding<idchargecomp_x_anchor_bindingFunctor, 2> idchargecomp_x_anchor_binding;
    struct idchargecomp_y_anchor_bindingFunctor {
    int operator()(hmimain *self) const;
};
    Qul::Private::Binding<idchargecomp_y_anchor_bindingFunctor, 2> idchargecomp_y_anchor_binding;
    struct chargingfailed_visible_bindingFunctor {
        bool operator()(hmimain *self) const;
    };
    Qul::Private::Binding<chargingfailed_visible_bindingFunctor, 0> chargingfailed_visible_binding;
    struct chargingfailed_height_bindingFunctor {
        int operator()(hmimain *self) const;
    };
    Qul::Private::Binding<chargingfailed_height_bindingFunctor, 0> chargingfailed_height_binding;
    struct chargingfailed_width_bindingFunctor {
        int operator()(hmimain *self) const;
    };
    Qul::Private::Binding<chargingfailed_width_bindingFunctor, 0> chargingfailed_width_binding;
    struct chargingfailed_x_anchor_bindingFunctor {
    int operator()(hmimain *self) const;
};
    Qul::Private::Binding<chargingfailed_x_anchor_bindingFunctor, 2> chargingfailed_x_anchor_binding;
    struct chargingfailed_y_anchor_bindingFunctor {
    int operator()(hmimain *self) const;
};
    Qul::Private::Binding<chargingfailed_y_anchor_bindingFunctor, 2> chargingfailed_y_anchor_binding;
    struct idchargingtext_y_anchor_bindingFunctor {
    int operator()(hmimain *self) const;
};
    Qul::Private::Binding<idchargingtext_y_anchor_bindingFunctor, 2> idchargingtext_y_anchor_binding;
    struct idchargingtext_color_bindingFunctor {
        Qul::PlatformInterface::Rgba32 operator()(hmimain *self) const;
    };
    Qul::Private::Binding<idchargingtext_color_bindingFunctor, 0> idchargingtext_color_binding;
    struct idchargingtext_text_bindingFunctor {
        Qul::Private::String operator()(hmimain *self) const;
    };
    Qul::Private::Binding<idchargingtext_text_bindingFunctor, 0> idchargingtext_text_binding;
    struct csrangeyval_x_anchor_bindingFunctor {
    int operator()(hmimain *self) const;
};
    Qul::Private::Binding<csrangeyval_x_anchor_bindingFunctor, 2> csrangeyval_x_anchor_binding;
    struct csrangeyval_y_anchor_bindingFunctor {
    int operator()(hmimain *self) const;
};
    Qul::Private::Binding<csrangeyval_y_anchor_bindingFunctor, 2> csrangeyval_y_anchor_binding;
    struct csrangeyval_text_bindingFunctor {
        Qul::Private::String operator()(hmimain *self) const;
    };
    Qul::Private::Binding<csrangeyval_text_bindingFunctor, 0> csrangeyval_text_binding;
    struct rectangle_12_x_anchor_bindingFunctor {
    int operator()(hmimain *self) const;
};
    Qul::Private::Binding<rectangle_12_x_anchor_bindingFunctor, 2> rectangle_12_x_anchor_binding;
    struct rectangle_12_y_anchor_bindingFunctor {
    int operator()(hmimain *self) const;
};
    Qul::Private::Binding<rectangle_12_y_anchor_bindingFunctor, 2> rectangle_12_y_anchor_binding;
    struct row_6_x_anchor_bindingFunctor {
    int operator()(hmimain *self) const;
};
    Qul::Private::Binding<row_6_x_anchor_bindingFunctor, 2> row_6_x_anchor_binding;
    struct row_6_y_anchor_bindingFunctor {
    int operator()(hmimain *self) const;
};
    Qul::Private::Binding<row_6_y_anchor_bindingFunctor, 2> row_6_y_anchor_binding;
    struct chargehrs_text_bindingFunctor {
        Qul::Private::String operator()(hmimain *self) const;
    };
    Qul::Private::Binding<chargehrs_text_bindingFunctor, 0> chargehrs_text_binding;
    struct chargemins_text_bindingFunctor {
        Qul::Private::String operator()(hmimain *self) const;
    };
    Qul::Private::Binding<chargemins_text_bindingFunctor, 0> chargemins_text_binding;
    struct rectangle_13_y_anchor_bindingFunctor {
    int operator()(hmimain *self) const;
};
    Qul::Private::Binding<rectangle_13_y_anchor_bindingFunctor, 2> rectangle_13_y_anchor_binding;
    struct row_7_x_anchor_bindingFunctor {
    int operator()(hmimain *self) const;
};
    Qul::Private::Binding<row_7_x_anchor_bindingFunctor, 2> row_7_x_anchor_binding;
    struct row_7_y_anchor_bindingFunctor {
    int operator()(hmimain *self) const;
};
    Qul::Private::Binding<row_7_y_anchor_bindingFunctor, 2> row_7_y_anchor_binding;
    struct energyval_text_bindingFunctor {
        Qul::Private::String operator()(hmimain *self) const;
    };
    Qul::Private::Binding<energyval_text_bindingFunctor, 0> energyval_text_binding;
    struct rectangle_14_x_anchor_bindingFunctor {
    int operator()(hmimain *self) const;
};
    Qul::Private::Binding<rectangle_14_x_anchor_bindingFunctor, 2> rectangle_14_x_anchor_binding;
    struct rectangle_14_y_anchor_bindingFunctor {
    int operator()(hmimain *self) const;
};
    Qul::Private::Binding<rectangle_14_y_anchor_bindingFunctor, 2> rectangle_14_y_anchor_binding;
    struct row_8_x_anchor_bindingFunctor {
    int operator()(hmimain *self) const;
};
    Qul::Private::Binding<row_8_x_anchor_bindingFunctor, 2> row_8_x_anchor_binding;
    struct row_8_y_anchor_bindingFunctor {
    int operator()(hmimain *self) const;
};
    Qul::Private::Binding<row_8_y_anchor_bindingFunctor, 2> row_8_y_anchor_binding;
    struct battempval_text_bindingFunctor {
        Qul::Private::String operator()(hmimain *self) const;
    };
    Qul::Private::Binding<battempval_text_bindingFunctor, 0> battempval_text_binding;
    struct idtempunit_y_anchor_bindingFunctor {
    int operator()(hmimain *self) const;
};
    Qul::Private::Binding<idtempunit_y_anchor_bindingFunctor, 2> idtempunit_y_anchor_binding;
    struct idtempunit_height_bindingFunctor {
        int operator()(hmimain *self) const;
    };
    Qul::Private::Binding<idtempunit_height_bindingFunctor, 0> idtempunit_height_binding;
    struct idtempunit_width_bindingFunctor {
        int operator()(hmimain *self) const;
    };
    Qul::Private::Binding<idtempunit_width_bindingFunctor, 0> idtempunit_width_binding;
    struct commontt_width_anchor_bindingFunctor {
    int operator()(hmimain *self) const;
};
    Qul::Private::Binding<commontt_width_anchor_bindingFunctor, 1> commontt_width_anchor_binding;
    struct commontt_height_anchor_bindingFunctor {
    int operator()(hmimain *self) const;
};
    Qul::Private::Binding<commontt_height_anchor_bindingFunctor, 1> commontt_height_anchor_binding;
    struct warningmsg_visible_bindingFunctor {
        bool operator()(hmimain *self) const;
    };
    Qul::Private::Binding<warningmsg_visible_bindingFunctor, 0> warningmsg_visible_binding;
    struct warningmsg_x_anchor_bindingFunctor {
    int operator()(hmimain *self) const;
};
    Qul::Private::Binding<warningmsg_x_anchor_bindingFunctor, 2> warningmsg_x_anchor_binding;
    struct warningmsg_text_bindingFunctor {
        Qul::Private::String operator()(hmimain *self) const;
    };
    Qul::Private::Binding<warningmsg_text_bindingFunctor, 0> warningmsg_text_binding;
    struct bgdate_visible_bindingFunctor {
        bool operator()(hmimain *self) const;
    };
    Qul::Private::Binding<bgdate_visible_bindingFunctor, 0> bgdate_visible_binding;
    struct bgdate_height_bindingFunctor {
        int operator()(hmimain *self) const;
    };
    Qul::Private::Binding<bgdate_height_bindingFunctor, 0> bgdate_height_binding;
    struct bgdate_width_bindingFunctor {
        int operator()(hmimain *self) const;
    };
    Qul::Private::Binding<bgdate_width_bindingFunctor, 0> bgdate_width_binding;
    struct daterect_x_anchor_bindingFunctor {
    int operator()(hmimain *self) const;
};
    Qul::Private::Binding<daterect_x_anchor_bindingFunctor, 3> daterect_x_anchor_binding;
    struct daterect_y_anchor_bindingFunctor {
    int operator()(hmimain *self) const;
};
    Qul::Private::Binding<daterect_y_anchor_bindingFunctor, 3> daterect_y_anchor_binding;
    struct row_9_x_anchor_bindingFunctor {
    int operator()(hmimain *self) const;
};
    Qul::Private::Binding<row_9_x_anchor_bindingFunctor, 2> row_9_x_anchor_binding;
    struct row_9_y_anchor_bindingFunctor {
    int operator()(hmimain *self) const;
};
    Qul::Private::Binding<row_9_y_anchor_bindingFunctor, 2> row_9_y_anchor_binding;
    struct tday_color_bindingFunctor {
        Qul::PlatformInterface::Rgba32 operator()(hmimain *self) const;
    };
    Qul::Private::Binding<tday_color_bindingFunctor, 0> tday_color_binding;
    struct tday_text_bindingFunctor {
        Qul::Private::String operator()(hmimain *self) const;
    };
    Qul::Private::Binding<tday_text_bindingFunctor, 0> tday_text_binding;
    struct tmon_color_bindingFunctor {
        Qul::PlatformInterface::Rgba32 operator()(hmimain *self) const;
    };
    Qul::Private::Binding<tmon_color_bindingFunctor, 0> tmon_color_binding;
    struct tmon_text_bindingFunctor {
        Qul::Private::String operator()(hmimain *self) const;
    };
    Qul::Private::Binding<tmon_text_bindingFunctor, 0> tmon_text_binding;
    struct tyear_color_bindingFunctor {
        Qul::PlatformInterface::Rgba32 operator()(hmimain *self) const;
    };
    Qul::Private::Binding<tyear_color_bindingFunctor, 0> tyear_color_binding;
    struct tyear_text_bindingFunctor {
        Qul::Private::String operator()(hmimain *self) const;
    };
    Qul::Private::Binding<tyear_text_bindingFunctor, 0> tyear_text_binding;
    struct bgtime_visible_bindingFunctor {
        bool operator()(hmimain *self) const;
    };
    Qul::Private::Binding<bgtime_visible_bindingFunctor, 0> bgtime_visible_binding;
    struct bgtime_height_bindingFunctor {
        int operator()(hmimain *self) const;
    };
    Qul::Private::Binding<bgtime_height_bindingFunctor, 0> bgtime_height_binding;
    struct bgtime_width_bindingFunctor {
        int operator()(hmimain *self) const;
    };
    Qul::Private::Binding<bgtime_width_bindingFunctor, 0> bgtime_width_binding;
    struct bgtime_x_anchor_bindingFunctor {
    int operator()(hmimain *self) const;
};
    Qul::Private::Binding<bgtime_x_anchor_bindingFunctor, 2> bgtime_x_anchor_binding;
    struct timerect_x_anchor_bindingFunctor {
    int operator()(hmimain *self) const;
};
    Qul::Private::Binding<timerect_x_anchor_bindingFunctor, 3> timerect_x_anchor_binding;
    struct timerect_y_anchor_bindingFunctor {
    int operator()(hmimain *self) const;
};
    Qul::Private::Binding<timerect_y_anchor_bindingFunctor, 3> timerect_y_anchor_binding;
    struct row_10_x_anchor_bindingFunctor {
    int operator()(hmimain *self) const;
};
    Qul::Private::Binding<row_10_x_anchor_bindingFunctor, 2> row_10_x_anchor_binding;
    struct row_10_y_anchor_bindingFunctor {
    int operator()(hmimain *self) const;
};
    Qul::Private::Binding<row_10_y_anchor_bindingFunctor, 2> row_10_y_anchor_binding;
    struct thour_color_bindingFunctor {
        Qul::PlatformInterface::Rgba32 operator()(hmimain *self) const;
    };
    Qul::Private::Binding<thour_color_bindingFunctor, 0> thour_color_binding;
    struct thour_text_bindingFunctor {
        Qul::Private::String operator()(hmimain *self) const;
    };
    Qul::Private::Binding<thour_text_bindingFunctor, 0> thour_text_binding;
    struct tmin_color_bindingFunctor {
        Qul::PlatformInterface::Rgba32 operator()(hmimain *self) const;
    };
    Qul::Private::Binding<tmin_color_bindingFunctor, 0> tmin_color_binding;
    struct tmin_text_bindingFunctor {
        Qul::Private::String operator()(hmimain *self) const;
    };
    Qul::Private::Binding<tmin_text_bindingFunctor, 0> tmin_text_binding;
    struct tampm_color_bindingFunctor {
        Qul::PlatformInterface::Rgba32 operator()(hmimain *self) const;
    };
    Qul::Private::Binding<tampm_color_bindingFunctor, 0> tampm_color_binding;
    struct tampm_text_bindingFunctor {
        Qul::Private::String operator()(hmimain *self) const;
    };
    Qul::Private::Binding<tampm_text_bindingFunctor, 0> tampm_text_binding;
    struct parking_visible_bindingFunctor {
        bool operator()(hmimain *self) const;
    };
    Qul::Private::Binding<parking_visible_bindingFunctor, 0> parking_visible_binding;
    struct parking_height_bindingFunctor {
        int operator()(hmimain *self) const;
    };
    Qul::Private::Binding<parking_height_bindingFunctor, 0> parking_height_binding;
    struct parking_width_bindingFunctor {
        int operator()(hmimain *self) const;
    };
    Qul::Private::Binding<parking_width_bindingFunctor, 0> parking_width_binding;
    struct hvbatteryfault_visible_bindingFunctor {
        bool operator()(hmimain *self) const;
    };
    Qul::Private::Binding<hvbatteryfault_visible_bindingFunctor, 0> hvbatteryfault_visible_binding;
    struct hvbatteryfault_height_bindingFunctor {
        int operator()(hmimain *self) const;
    };
    Qul::Private::Binding<hvbatteryfault_height_bindingFunctor, 0> hvbatteryfault_height_binding;
    struct hvbatteryfault_width_bindingFunctor {
        int operator()(hmimain *self) const;
    };
    Qul::Private::Binding<hvbatteryfault_width_bindingFunctor, 0> hvbatteryfault_width_binding;
    struct lvbatttery_visible_bindingFunctor {
        bool operator()(hmimain *self) const;
    };
    Qul::Private::Binding<lvbatttery_visible_bindingFunctor, 0> lvbatttery_visible_binding;
    struct lvbatttery_height_bindingFunctor {
        int operator()(hmimain *self) const;
    };
    Qul::Private::Binding<lvbatttery_height_bindingFunctor, 0> lvbatttery_height_binding;
    struct lvbatttery_width_bindingFunctor {
        int operator()(hmimain *self) const;
    };
    Qul::Private::Binding<lvbatttery_width_bindingFunctor, 0> lvbatttery_width_binding;
    struct lvbatttery_x_anchor_bindingFunctor {
    int operator()(hmimain *self) const;
};
    Qul::Private::Binding<lvbatttery_x_anchor_bindingFunctor, 2> lvbatttery_x_anchor_binding;
    struct bmsfault_visible_bindingFunctor {
        bool operator()(hmimain *self) const;
    };
    Qul::Private::Binding<bmsfault_visible_bindingFunctor, 0> bmsfault_visible_binding;
    struct bmsfault_height_bindingFunctor {
        int operator()(hmimain *self) const;
    };
    Qul::Private::Binding<bmsfault_height_bindingFunctor, 0> bmsfault_height_binding;
    struct bmsfault_width_bindingFunctor {
        int operator()(hmimain *self) const;
    };
    Qul::Private::Binding<bmsfault_width_bindingFunctor, 0> bmsfault_width_binding;
    struct bmsfault_x_anchor_bindingFunctor {
    int operator()(hmimain *self) const;
};
    Qul::Private::Binding<bmsfault_x_anchor_bindingFunctor, 2> bmsfault_x_anchor_binding;
    struct thernalrunaway_visible_bindingFunctor {
        bool operator()(hmimain *self) const;
    };
    Qul::Private::Binding<thernalrunaway_visible_bindingFunctor, 0> thernalrunaway_visible_binding;
    struct thernalrunaway_height_bindingFunctor {
        int operator()(hmimain *self) const;
    };
    Qul::Private::Binding<thernalrunaway_height_bindingFunctor, 0> thernalrunaway_height_binding;
    struct thernalrunaway_width_bindingFunctor {
        int operator()(hmimain *self) const;
    };
    Qul::Private::Binding<thernalrunaway_width_bindingFunctor, 0> thernalrunaway_width_binding;
    struct thernalrunaway_x_anchor_bindingFunctor {
    int operator()(hmimain *self) const;
};
    Qul::Private::Binding<thernalrunaway_x_anchor_bindingFunctor, 2> thernalrunaway_x_anchor_binding;
    struct batlowcoolant_visible_bindingFunctor {
        bool operator()(hmimain *self) const;
    };
    Qul::Private::Binding<batlowcoolant_visible_bindingFunctor, 0> batlowcoolant_visible_binding;
    struct batlowcoolant_height_bindingFunctor {
        int operator()(hmimain *self) const;
    };
    Qul::Private::Binding<batlowcoolant_height_bindingFunctor, 0> batlowcoolant_height_binding;
    struct batlowcoolant_width_bindingFunctor {
        int operator()(hmimain *self) const;
    };
    Qul::Private::Binding<batlowcoolant_width_bindingFunctor, 0> batlowcoolant_width_binding;
    struct batlowcoolant_x_anchor_bindingFunctor {
    int operator()(hmimain *self) const;
};
    Qul::Private::Binding<batlowcoolant_x_anchor_bindingFunctor, 2> batlowcoolant_x_anchor_binding;
    struct deviceinfo_x_anchor_bindingFunctor {
    int operator()(hmimain *self) const;
};
    Qul::Private::Binding<deviceinfo_x_anchor_bindingFunctor, 2> deviceinfo_x_anchor_binding;
    struct deviceinfo_y_anchor_bindingFunctor {
    int operator()(hmimain *self) const;
};
    Qul::Private::Binding<deviceinfo_y_anchor_bindingFunctor, 2> deviceinfo_y_anchor_binding;
    struct deviceinfo_visible_bindingFunctor {
        bool operator()(hmimain *self) const;
    };
    Qul::Private::Binding<deviceinfo_visible_bindingFunctor, 0> deviceinfo_visible_binding;
    struct deviceinfo_color_bindingFunctor {
        Qul::PlatformInterface::Rgba32 operator()(hmimain *self) const;
    };
    Qul::Private::Binding<deviceinfo_color_bindingFunctor, 0> deviceinfo_color_binding;
    struct devicdetails_color_bindingFunctor {
        Qul::PlatformInterface::Rgba32 operator()(hmimain *self) const;
    };
    Qul::Private::Binding<devicdetails_color_bindingFunctor, 0> devicdetails_color_binding;
    struct devicdetails_x_anchor_bindingFunctor {
    int operator()(hmimain *self) const;
};
    Qul::Private::Binding<devicdetails_x_anchor_bindingFunctor, 2> devicdetails_x_anchor_binding;
    struct swver_color_bindingFunctor {
        Qul::PlatformInterface::Rgba32 operator()(hmimain *self) const;
    };
    Qul::Private::Binding<swver_color_bindingFunctor, 0> swver_color_binding;
    struct swver1_color_bindingFunctor {
        Qul::PlatformInterface::Rgba32 operator()(hmimain *self) const;
    };
    Qul::Private::Binding<swver1_color_bindingFunctor, 0> swver1_color_binding;
    struct seversion_color_bindingFunctor {
        Qul::PlatformInterface::Rgba32 operator()(hmimain *self) const;
    };
    Qul::Private::Binding<seversion_color_bindingFunctor, 0> seversion_color_binding;
    struct seversion_text_bindingFunctor {
        Qul::Private::String operator()(hmimain *self) const;
    };
    Qul::Private::Binding<seversion_text_bindingFunctor, 0> seversion_text_binding;
    struct hwver_color_bindingFunctor {
        Qul::PlatformInterface::Rgba32 operator()(hmimain *self) const;
    };
    Qul::Private::Binding<hwver_color_bindingFunctor, 0> hwver_color_binding;
    struct hwver1_color_bindingFunctor {
        Qul::PlatformInterface::Rgba32 operator()(hmimain *self) const;
    };
    Qul::Private::Binding<hwver1_color_bindingFunctor, 0> hwver1_color_binding;
    struct hwversion_color_bindingFunctor {
        Qul::PlatformInterface::Rgba32 operator()(hmimain *self) const;
    };
    Qul::Private::Binding<hwversion_color_bindingFunctor, 0> hwversion_color_binding;
    struct hwversion_text_bindingFunctor {
        Qul::Private::String operator()(hmimain *self) const;
    };
    Qul::Private::Binding<hwversion_text_bindingFunctor, 0> hwversion_text_binding;
    struct slnum_color_bindingFunctor {
        Qul::PlatformInterface::Rgba32 operator()(hmimain *self) const;
    };
    Qul::Private::Binding<slnum_color_bindingFunctor, 0> slnum_color_binding;
    struct slnum1_color_bindingFunctor {
        Qul::PlatformInterface::Rgba32 operator()(hmimain *self) const;
    };
    Qul::Private::Binding<slnum1_color_bindingFunctor, 0> slnum1_color_binding;
    struct slnumtxt_color_bindingFunctor {
        Qul::PlatformInterface::Rgba32 operator()(hmimain *self) const;
    };
    Qul::Private::Binding<slnumtxt_color_bindingFunctor, 0> slnumtxt_color_binding;
    struct slnumtxt_text_bindingFunctor {
        Qul::Private::String operator()(hmimain *self) const;
    };
    Qul::Private::Binding<slnumtxt_text_bindingFunctor, 0> slnumtxt_text_binding;
};

